### PR TITLE
Passively discover devices and update IP addresses

### PR DESCRIPTION
**Pull request by postlund**
Here we go... With this change, discovery packets from Tuya devices are constantly monitored and cached. If a device is found and the IP address does not match what is currently stored in its config entry, the config entry is updated with the correct address and and reloaded. This magically fix things if a device changes IP address. It works in YAML mode as well, but an updated address is not written back to YAML (of course).

Since there now is a device cache that is constantly updated, we can also say goodbye to the initial scan delay when adding a new device from config flow. It's instant!

Since devices send these packets without us having to ask for them, this change has virtually no impact when it comes to performance 👍 One thing that might be considered missing is purging of old devices. If a device is found, it will stay in the cache until Home Assistant is restarted. Can be fixed later if we find this to be a problem.

### CODE REVIEW

**Comment by postlund** [comment]
@rospogrigio You should try this. It's not done yet, I need to polish it a bit. Will add you as a reviewer once done.

**Comment by carryonrewardless** [comment]
I am getting some variability with this PR. 
I have three identical devices on my network to which I have applied the same config yaml settings and have the following observations over the last 48 hrs.
I had to play around with my router DHCP settings and found that the Discovery process was not connecting them after the IP address changed. Tried a Reload of Localtuya and a HA restart.  I had to manually set the IP address in the yaml before they would re-connect.

One device reports a current that is not consistent with its corresponding Power reading - which I have reason to agree with. The current reading is at fault.
Another device does not generate a Voltage entity and yet it displays a voltage reading in the switch entity details.
These measurements all worked correctly before the PR86 was implemented.
HTH

**Comment by postlund** [comment]
The discovery will only work if Home Assistant can pick up the broadcast messages, so maybe there's a problem with that. How are you Home Assistant setup? On the same physical network (I.e. no VLAN)? Host mode if you use docker? You can check if the devices appear in the list when adding via config flow. If they don't appear there, something isn't working (you need to remove them from YAML first though as the config flow doesn't show configured devices). Might be worth trying with and without this PR.

The voltage attribute and the entity (I assume `sensor`) are two different things and are not connected to each other in any ways. They just happen to show the same value. Why it isn't setup I don't know, as the discovery changes here shouldn't mess with entity setup.

**Comment by carryonrewardless** [comment]
I have a Supervised installation on Raspbian Buster with everything on the same network.
Not sure what is meant by "when adding via config flow".
I have added some error messages from the log and also the config.yaml lines in this https://pastebin.com/fqawMZbr
Maybe this helps. Thanks

**Comment by postlund** [comment]
Those errors are unrelated to this, but we should look into those as well. If you go to Configuration -> Integrations and try to add a device from there, is the device list empty (just `...`) or do you see any devices? Make sure at least one device is not configured via YAML as already configured devices will not show up.

**Comment by carryonrewardless** [comment]
I first just commented out all lines for the first device in the config yaml and then restarted HA. The Integration showed the 3 devices each with 4 entities.
So then I commented out the other devices including the localtuya: line and restarted HA.
It still showed all 3 devices so I could see no prompt or options to add a device.
image
image

Sorry I don't feel like I am helping your project move forward. Do you need me to delete everything from the custom_components folder and do a clean install?

**Comment by postlund** [comment]
Right, forgot to mention that. The YAML config results in a config entry and if it already exists, current config will be overwritten. Removing the YAML config does not remove the config entry, you have to manually do that. Short story: you need to manually remove devices from the Integrations page.

**Comment by carryonrewardless** [comment]
Seems like I have to remove the Integration and start again as I see no direct way to remove the Devices. I get this when I attempt to remove the Entities.
image

**Comment by postlund** [comment]
Ok, didn't know about that. You will have to re-add in YAML, start Home Assistant, remove from integrations, remove from YAML and restart.

You should only have a `localtuya` under `custom_components`, so whatever is in `/homeassistant/share/hassio/homeassistant/custom_components/localtuya-homeassistant/custom_components/` will not be used.

**Comment by postlund** [comment]
Maybe you have been running with the wrong version of the component and that's why it doesn't work?

**Comment by carryonrewardless** [comment]
I will check a few of these things and report back.

**Comment by postlund** [comment]
Sounds great! I just rebased with master to get all them at has been merged lately. Make sure you try this latest update.

**Comment by postlund** [comment]
@rospogrigio I think this is ready for review as well, but we shouldn't merge until @carryonrewardless has tested it and reported back.

**Comment by carryonrewardless** [comment]
>  will have to re-add in YAML, start Home Assistant, remove from integrations, remove from YAML and restart.

I did this.  Then I deleted all localtuya files and folders from custom_components so I could do a clean install.
Then I did:
```
sudo git clone https://github.com/rospogrigio/localtuya-homeassistant.git
git branch
sudo git fetch 
sudo git branch  discovery_updates
sudo git checkout origin/discovery_updates
```

and then copied the localtuya folder to custom_components and did a HA re-start.
When I clicked + in Integrations it found the localtuya Integration ok but did not set the Integration up. So no Discovery drop-down menu appeared.  I tried this a few times.
The logs show:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 136, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 69, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 131, in async_init
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 204, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/localtuya/config_flow.py", line 212, in async_step_user
    devices = self.hass.data[DOMAIN][DATA_DISCOVERY].devices
KeyError: 'localtuya'

```
I have left it with nothing in the config yaml at this stage.  Awaiting your direction. My tz is UTC+11 so I need some sleep. Ciao for now.

**Comment by postlund** [comment]
Now it seems to be the correct code that is running 👍 And now I see that I have not done this properly. I need to think about the right way to set this up, will report back when I have a solution.

**Comment by postlund** [comment]
Just to clarify what is happening here. When the component (`localtuya`) is set up, the broadcast handling is configured and found devices are cached. I then re-use the results when initiating a config flow, but since the component is only set up if there's something that trigger it, I.e. a config entry or config in YAML. If none of those exists, the component is not set up and there will be no cache available for the config flow. I need to add scanning the in the config flow In case no device has been previously added.

**Comment by postlund** [comment]
@carryonrewardless I have now changed to use manual discovery when no device has been set up, so hopefully it should work now.

**Comment by carryonrewardless** [comment]
Thanks Discovery is now working correctly finding the 3 devices including their IP addresses. 
Now not getting the entities created for current, power and voltage. Only for the switch.
Also no apparent way to add the next device.
Tried a restart of HA but still no other entities.

**Comment by postlund** [comment]
Yes, you need to define `sensor` entities if you want them as individual sensors. The values you specify when adding a switch are added as state attributes. Just continue adding devices under `localtuya:` as it takes a list:

```yaml
localtuya:
  - host: 192.168.1.1
    device_id: xxxxx
    local_key: xxxxx
    friendly_name: Tuya Device
    protocol_version: "3.3"
    entities:
      ...
  - host: 192.168.1.2
    device_id: yyy
    local_key: zzz
    friendly_name: Tuya Device
    protocol_version: "3.3"
    entities:
      ...
```

**Comment by carryonrewardless** [comment]
So only the first device can be Discovered? 
Should we not have a button to start Discovery again for each new Device to be added?

**Comment by postlund** [comment]
> So only the first device can be Discovered?
> Should we not have a button to start Discovery again for each new Device to be added?

You will have to manually adding new devices via the +-button when doing it from Integrations. That's how it's designed (I can't do anything about it).

**Comment by carryonrewardless** [comment]
The Discovery process only seems to provide for one Device to be selected and added. The other Discovered Devices can no longer be selected anywhere.
Even when I remove the Integration and add it back so it is empty, I can still only see how to add one Device when using the + button.  The "Do not add more entities" tick box when left empty does not allow for another Device to be added. 
You cannot get back to this pull-down to select the next Device.
image

**Comment by postlund** [comment]
I'm not sure what you mean? You can only add one device at the time. If you press +, pick one device from the list (in the drop down list depicted in your image), fill in basic details, add an entity or more, make sure you the "Do not add more entities" and finish. You should be back at the integrations page and your device should be listed. If you now press + again and pick Localtuya, is the list empty now? If it is, exit the flow, wait ten seconds and check again. Also check the error log.

**Comment by carryonrewardless** [comment]
Oh that explains it.  I was not clicking on the + button you refer to as I thought that was just to add a _new Integration_. Very confusing and not intuitive.
Can we not add a + button within the Localtuya Integration window? 
I can now see that the Discovery is working as was intended but I encourage you to consider adding a button on the Localtuya window dedicated to adding new Devices.

**Comment by postlund** [comment]
Ok,great 👍 It's not possible to do that, the frontend/Home Assistant is designed this way and no way around it. Just think of the + button adding one new device of something as that's what it means.

**Comment by carryonrewardless** [comment]
Ok then I will say a big thanks for getting this built. It's a great innovation and solution for updating IP addresses.

**Comment by postlund** [comment]
Thank you for testing 👍 I see great potential here as well, especially for situations like #89 where I hope this change can solve that for me.

**Review by rospogrigio — APPROVED** [review]

**Pull request merged**
