### PR TITLE
Improve discovery error output

### PR DESCRIPTION
**Pull request by postlund**
This one is for you @rospogrigio 😉

### CODE REVIEW

**Review by rospogrigio — APPROVED** [review]

**Comment by postlund** [comment]
I don't understand why Actions is acting up... The jobs obviously run as expected but are not reported back. Whyyyy...

**Comment by postlund** [comment]
@rospogrigio Would you mind bumping my permissions to the repo for a while so I can troubleshoot why the actions aren't reported correctly?

**Comment by postlund** [comment]
Ok, so I just updated the commit time and pushed again and now it works again.. Maybe hiccup yesterday then.

**Comment by postlund** [comment]
And then comes the GitHub actins bot and pushed something. Why is that...

@KTibow Hey! We've see some issues since we merged the changes moving to your blueprint. Whenever I push something the actions are run and reported on back to the PR, but then comes the GitHub bot and makes a force push which breaks everything (checks are never resolved). This didn't happen before the change. Do you have any ideas as I'm out of them?

**Comment by postlund** [comment]
Looking at the commit, it seems like isort is kicking in and sorting the imports (something we don't do with tox currently). The updates are amended and pushed, but this for some reason does not trigger a re-run of the actions.

**Comment by postlund** [comment]
So after sorting the imports it worked fine.

**Comment by KTibow** [comment]
Do you still need me? I can add an option to disable isort if you need.

**Comment by postlund** [comment]
@KTibow Yes and no. I mean, we know what the problem is now and how we can circumvent it. But it would be interesting to know why the jobs won't run. Otherwise it would be better if the action just verified things and failed hard if something is wrong. Now it becomes a silent error which is hard to debug.

**Comment by KTibow** [comment]
Can you explain? Can you provide links to the failing actions? (Sorry, was at work, couldn't respond)

**Pull request merged**
