### PR TITLE
Add Brazilian Portuguese translation 

### PR DESCRIPTION
**Pull request by LeandroIssa**
Pleanse, add brazilian portuguese translation

### CODE REVIEW

**Comment by LeandroIssa** [comment]
Please someone approve, it's just a translation.

**Review by alanmgomes — APPROVED** [review]
É uma tradução válida para o portguês, parabéns.
It is a valid translation into Portuguese.

**Review by alanmgomes — APPROVED** [review]
É uma tradução válida para o portguês, parabéns.
It is a valid translation into Portuguese.

**Comment by LeandroIssa** [comment]
@rospogrigio please accept the translation, it's just a translation and there will be no changes to anything in the component code!
Only 5% of Brazilians understand English and only 3% are fluent! It is important to have Local Tuya in Brazilian Portuguese.
Please!

**Pull request merged**
