### PR TITLE
Stability fixes

### PR DESCRIPTION
**Pull request by rospogrigio**
Improved logging.
Introduced local_key update on device edit.
Fixed devices not reconnecting any more in certain cases.

### CODE REVIEW

**Comment by plandregan** [comment]
Thank you for your continued work on this, Hope the stability fix's the disappearing 3.4 devices and random crashes of the Integration, needing a HA restart. Once th8is goes to the master I hope to update my 5.0.0 to 5.0.1

**Comment by rospogrigio** [comment]
Why don't you try this PR and provide feedback instead of waiting for it to merge into master?

**Comment by plandregan** [comment]
How do I load a PR, I just tried in HACS and set it to load Beta, but
nothing showed up.

Happy to test if I knew how.

**Comment by rospogrigio** [comment]
There are several ways but you need to be a bit advanced. You can use github, or you could just download the changed files and replace the originals you find in custom_components/localtuya. Let me know if you succeed and how it goes...

**Comment by rospogrigio** [comment]
You probably have done something wrong. When you copy the files, you can just ignore those in the .github folder, just replace the .py files.
Let me know

**Comment by rospogrigio** [comment]
> @rospogrigio: If you could enable the HACS beta version support for the fix PR's, it would really help to get more testers and to get people with the problem(s) they fix to actually test the PR before it gets released. This would be especially helpful since Local Tuya is an "official" HACS integration in the default Store repository. As @plandregan stated, they did try to load and test the PR via the HACS beta integration, but since it wasn't set up in HACS for beta testing, it didn't work.

I didn't know about this HACS beta support, how does it work? How can I enable it?

**Comment by cvroque** [comment]
I've been using the beta release for a few hours now and it's been 100% stable, even for lights that were turned off and on manually a bunch of times which was a frequent issue earlier. If anything changes I'll make sure to update here, thanks a lot!

**Comment by sibowler** [comment]
Hi @rospogrigio - Did you want to include the changes in PR #1273 in this one too?

**Comment by plandregan** [comment]
So far, no lock ups and no missing devices.
Using the 5.1.0beta0

**Comment by rospogrigio** [comment]
> Hi @rospogrigio - Did you want to include the changes in PR #1273 in this one too?

Yeah, that was the plan but I wanted to fully understand what you did first, and test it a little bit. Can you merge this branch in there first maybe?

**Comment by xkuizit** [comment]
Been testing this PR. It is certainly more stable than 5.0.0. I did have a couple devices lockup last night though. Had to reload localtuya. Did not require HA restart. I will keep an eye out for more on this. Looks like during the reconnection flow it failed and gave up. 

I'm still seeing a lot of disconnects even though ping for my devices are not showing any packet loss. Disconnect roughly every 40 mins or so. I'm also seeing that initial connection time is much shorter than reconnection time. 

As an example here is the initial connection logs (from start to finish only 2 seconds):
```
2023-02-08 16:53:58.645 INFO (MainThread) [custom_components.localtuya.common] [610...66b] async_connect: 0 None None
2023-02-08 16:53:58.812 INFO (MainThread) [custom_components.localtuya.common] [610...66b] Trying to connect to 192...12...
2023-02-08 16:53:59.555 INFO (MainThread) [custom_components.localtuya.common] [610...66b] Successfully connected to 192...12
2023-02-08 16:53:59.561 DEBUG (MainThread) [custom_components.localtuya.pytuya] [610...66b] Started heartbeat loop
```
But for a reconnection the time from async_connect to successful connection is much larger (30 secs - have seen over a minute in some cases):
```
2023-02-08 18:22:20.470 DEBUG (MainThread) [custom_components.localtuya.pytuya] [610...66b] Command 9 waiting for seq. number -100
2023-02-08 18:22:25.471 WARNING (MainThread) [custom_components.localtuya.pytuya] [610...66b] Command 9 timed out waiting for sequence number -100
2023-02-08 18:22:25.475 DEBUG (MainThread) [custom_components.localtuya.pytuya] [610...66b] Heartbeat failed due to timeout, disconnecting
2023-02-08 18:22:25.475 DEBUG (MainThread) [custom_components.localtuya.pytuya] [610...66b] Connection lost: None
2023-02-08 18:22:25.476 WARNING (MainThread) [custom_components.localtuya.common] [610...66b] Disconnected - waiting for discovery broadcast

2023-02-08 18:22:53.442 INFO (MainThread) [custom_components.localtuya.common] [610...66b] async_connect: 0 None None
2023-02-08 18:22:53.442 INFO (MainThread) [custom_components.localtuya.common] [610...66b] Trying to connect to 192...12...
2023-02-08 18:23:22.604 INFO (MainThread) [custom_components.localtuya.common] [610...66b] Successfully connected to 192...12
2023-02-08 18:23:22.605 DEBUG (MainThread) [custom_components.localtuya.pytuya] [610...66b] Started heartbeat loop

```

**Comment by sibowler** [comment]
Hi @rospogrigio - I've merged these changes into PR #1273. I've been testing the last couple of days and so far it's all working as expected.

**Comment by xkuizit** [comment]
Been running 24 hours with no issues.

**Comment by peterhagg** [comment]
Is beta version support active in HACS now? Which version do I have installed? States "v5.0.0" in upper left corner but it also state "V5.1.0-BETA0" on the line below (is this latest release)? How do I install it från HACS?

IMG_6565

**Comment by plandregan** [comment]
Yes he has got beta support. This beta is related to PR1276

**Comment by rospogrigio** [comment]
> Is beta version support active in HACS now? Which version do I have installed? How do I install it från HACS?

You are still running 5.0.0. You need to press "re-download" and then check the "show beta versions" to install the 5.1.0beta0.

**Comment by peterhagg** [comment]
Thanks for help. I have communication problem with one device, would like to see if this beta version will help :-) 
I can't find the toogle switch to enable beta after re-download. Still have v5.0.0. Any more setting to be done in HACS? I will  try to update files manually with Samba also.

**Comment by xkuizit** [comment]
@rospogrigio So far things still looking pretty stable. One thing is that re-connects seem to be takin longer compared to 3.x. 

It looks like cleanup of listeners can take ~30 secs sometimes. And then from async_connect to successful connection can take another 30-60 seconds. However the initial async_connect takes less than a few seconds. For some reason in the reconnect case async_connect is getting backed up and taking much longer.

**Review by Alloc186 — APPROVED** [review]

**Review by Alloc186 — APPROVED** [review]

**Pull request merged**
