### PR TITLE
Optional Light variable to reverse color temp

### PR DESCRIPTION
**Pull request by lsaadeh**
feature resolves following issue: https://github.com/rospogrigio/localtuya/issues/615

Config for **Arlec 130cm White 4 Blade Grid Connect Smart DC Ceiling Fan With Remote DCF4002WHA**
```
localtuya:
  - host: <device_ip>
    device_id: <device_id>
    local_key: <local_key>
    friendly_name: Ceiling Fan
    protocol_version: "3.3"
    entities:
      - platform: light
        friendly_name: Light
        brightness: 10
        brightness_lower: 0
        brightness_upper: 100
        color_temp: 11
        color_temp_reverse: true
        color_temp_min_kelvin: 2700
        color_temp_max_kelvin: 6500
        id: 9
      - platform: fan
        friendly_name: Fan
        fan_speed_control: 3
        fan_speed_low: "2"
        fan_speed_medium: "3"
        fan_speed_high: "4"
        id: 1
```

### CODE REVIEW

**Comment by lsaadeh** [comment]
Hi @rospogrigio, @postlund, @ultratoto14, if you could please review this pr when you have a moment thank you.

**Comment by wookie666** [comment]
Only issue I had is I have #542 also in my system and these changes do not work with those files. 

Would need to group both prs together for this to work

**Comment by lsaadeh** [comment]
> Only issue I had is I have #542 also in my system and these changes do not work with those files.
> 
> Would need to group both prs together for this to work

For testing purposes, you will need to deploy this code base independently (without any other code changes).
Once my changes to the light temp have been reviewed you can switch back to using the new fan PR.

**Comment by lsaadeh** [comment]
@darek-margas, I saw you created a PR for the Arlec ceiling fan and thought this could be of use to you.

**Comment by darek-margas** [comment]
@Isaadeh
> I saw you created a PR for the Arlec ceiling fan and thought this could be of use to you.

Thanks, mine had no light. Anyway, after a while I made PCB with ESP and replaced original one, now run ESPhome in these Arlecs.

**Comment by lsaadeh** [comment]
Just for clarity @PaulioArmani, this is the pr you will need to test to add a variable to reverse the color temp.
Once my changes to the light temp have been reviewed and tested you can switch back to using the new fan PR.
hopefully in the future well have both prs merged in master.

**Comment by lsaadeh** [comment]
Hi @rospogrigio, could you please approve this PR?

**Comment by lsaadeh** [comment]
@rospogrigio, could I get some love on this one please <3

**Review by rospogrigio — APPROVED** [review]

**Comment by rospogrigio** [comment]
Merged #652.

**Comment by PaulioArmani** [comment]
I have tested this and added to the fan fixes on another PR #542. Now everything is working perfectly for my Arlec Grid Connect Smart Fans as this was the final piece of the puzzle. The only issue was I wasn't sure how to reverse the colour temp at first as the check box isn't labelled.  Add the below to both "Add new entity" and "Entity Configuration" sections of en.json so the checkbox has a label. 

"color_temp_reverse": "Color Temperature Reverse",

**Comment by PaulioArmani** [comment]
> Just for clarity @PaulioArmani, this is the pr you will need to test to add a variable to reverse the color temp. Once my changes to the light temp have been reviewed and tested you can switch back to using the new fan PR. hopefully in the future well have both prs merged in master.

Thanks @lsaadeh, I have both PR's merged in my own HA instance and all working perfectly for light and fan.

**Comment by wookie666** [comment]
> I have tested this and added to the fan fixes on another PR #542. Now everything is working perfectly for my Arlec Grid Connect Smart Fans as this was the final piece of the puzzle. The only issue was I wasn't sure how to reverse the colour temp at first as the check box isn't labelled. Add the below to both "Add new entity" and "Entity Configuration" sections of en.json so the checkbox has a label.
> 
> "color_temp_reverse": "Color Temperature Reverse",

I did the same and noticed the checkbox unlabelled too

**Comment by rospogrigio** [comment]
In case  you can update this PR or create a new one to fix the missing label...

**Comment by lsaadeh** [comment]
@rospogrigio @PaulioArmani  @wookie666 I use yaml to configure my devices sorry for missing this one, could you test the fix in this pr: https://github.com/rospogrigio/localtuya/pull/671/files

**Pull request merged**
