### PR TITLE
Fix white only scene on RGBW lights

### PR DESCRIPTION
**Pull request by ultratoto14**
When a scene is created using the HA scene editor, it stores the complete status of the light.
When the scene is applied, HA scene this complete status.

In my previous PR, I forced the color to hs [0, 0] to be sure that the color picker return to white when we use color_temp
With that, the scene editor will now store this white value. If we detect this value, we force ignore the color and only set the white related settings.

### CODE REVIEW

**Comment by SmartM-ui** [comment]
> When a scene is created using the HA scene editor, it stores the complete status of the light.
> When the scene is applied, HA scene this complete status.
> 
> In my previous PR, I forced the color to hs [0, 0] to be sure that the color picker return to white when we use color_temp
> With that, the scene editor will now store this white value. If we detect this value, we force ignore the color and only set the white related settings.

Hi @ultratoto14 ,
Can you explain to me what you mean by creating a scene using HA?
If you explain the test to be performed, I'll try :-)

**Comment by ultratoto14** [comment]
Hi @SmartM-ui, i mean  [scene editor](https://www.home-assistant.io/docs/scene/editor/#:~:text=If%20you%20just%20created%20a,right%20corner%20to%20get%20started.)
The process should be:

- choose a tuya RGBW light.
- set it to white and choose a color_temp somewhere in the middle 
- save the scene
- change the color_temp to anything else than in the scene
- change to color
- apply the scene
- check that color_temp is ok, and bulb is respecting what has been saved.

Without this patch, we can have different behaviour.

Thanks for testing.

**Comment by SmartM-ui** [comment]
> Hi @SmartM-ui, i mean [scene editor](https://www.home-assistant.io/docs/scene/editor/#:~:text=If%20you%20just%20created%20a,right%20corner%20to%20get%20started.)
> The process should be:
> 
>     * choose a tuya RGBW light.
> 
>     * set it to white and choose a color_temp somewhere in the middle
> 
>     * save the scene
> 
>     * change the color_temp to anything else than in the scene
> 
>     * change to color
> 
>     * apply the scene
> 
>     * check that color_temp is ok, and bulb is respecting what has been saved.
> 
> 
> Without this patch, we can have different behaviour.
> 
> Thanks for testing.

Hi @ultratoto14 ,
here I am, I just installed your latest work "localtuya-light_scene_fix"!
I hope I understand the test to be carried out, because I had never used the Home Assistant "scenes" :-)

1) I set a scene with white color and color temperature in the center of the slider and saved the scene.
2) I turned on the bulb and set the color temperature "cold" (end of the slider) and then I set the color red
3) I went back to the "scenes" and applied the previously saved scene

The light bulb returned to white, but the slider remained at the "cold" color temperature and did not return to the center of the slider as it was previously saved in the scene.

I tried the same situation with the localtuya version prior to your work and the scenes do not bring the light bulb back to white, but change to the light "violet" color.

PS thanks to you for developing this component!

**Comment by ultratoto14** [comment]
Hi @SmartM-ui, thanks again for testing, seems that the problem comes from the changed i made to put back the color picker to white (if you remember).
Do you have non-tuya RGB+W light ? Just to test if the color_picker keeping the previously chosen color is not the default behavior ?

I mean, when we change to color, the color_temp slider stay where it is, only the bulb icon color is changed. It seems not so bad, what do you think ?
If i remove the color picker fix, the scene is stored without color arguments that prevent HA to send color_temp data to bulb.

**Comment by SmartM-ui** [comment]
> Hi @SmartM-ui, thanks again for testing, seems that the problem comes from the changed i made to put back the color picker to white (if you remember).
> Do you have non-tuya RGB+W light ? Just to test if the color_picker keeping the previously chosen color is not the default behavior ?
> 
> I mean, when we change to color, the color_temp slider stay where it is, only the bulb icon color is changed. It seems not so bad, what do you think ?
> If i remove the color picker fix, the scene is stored without color arguments that prevent HA to send color_temp data to bulb.

Hi @ultratoto14 ,
of course I remember your change, I asked for it :-)

Unfortunately I only have TUYA bulbs, I can't try scenes with other bulbs.

However, this new version is better than the previous one.
I left this!

This change of yours made me think of a request to make ... I open a new issue.

Thanks again

**Comment by ultratoto14** [comment]
Hi @postlund , @rospogrigio, @SmartM-ui  need your advice on this one.
During the PR for the support of RGB, i fixed a "bug" 
LightData
When we switch from color (left) to white (right), the bulb color is changed but the color picker keep the last set color. 
I fixed that by forcing the color to [ 0, 0 ]. But it seems to not be the normal case. It should be None as @postlund did in his PR.

Setting to [0,0] generates an unwanted behavior, when using white only scene, the HA scene editor is storing the bulb state and stores the color_temp and this [ 0, 0 ] color. When applying the state as there is some color, HA does not send the color_temp to the light in the turn_on call.

So the normal scene behavior and internal way of managing color and color_temp is that when in white, color is None. I do not know if when in color, color_temp should be None too. 

Should we remove this forcing and go back to a color picker temporary keeping the previous color as the bulb icon reflects the real setting ?

**Comment by ultratoto14** [comment]
@SmartM-ui, @postlund , @rospogrigio just found that : [https://github.com/home-assistant/frontend/issues/6091](https://github.com/home-assistant/frontend/issues/6091)

Seems that only relevant data should be returned, so in case Color, color_temp should be none and so one.
It means that the color picker behavior, keeping set on the last selected is expected.

**Comment by ultratoto14** [comment]
@rospogrigio or @postlund. This is ready for review.

**Comment by SmartM-ui** [comment]
> @SmartM-ui, @postlund , @rospogrigio just found that : [home-assistant/frontend#6091](https://github.com/home-assistant/frontend/issues/6091)
> 
> Seems that only relevant data should be returned, so in case Color, color_temp should be none and so one.
> It means that the color picker behavior, keeping set on the last selected is expected.

Hi,
as soon as possible I try your latest fix!

**Comment by ultratoto14** [comment]
Hi @SmartM-ui 
So the test should be same as before, you can also verify that:

- In case we use a color in the scene editor, color_temp is not present in scenes.yaml
- In case we use a color_temp in the scene editor, hs, rgb and xy are not present in scenes.yaml

Thanks for testing.

**Comment by ultratoto14** [comment]
Hi @postlund, @SmartM-ui confirmed the behavior. It could merged.

**Review by postlund — APPROVED** [review]

**Pull request merged**
