### PR TITLE
fix: major sync issue on mostly static entities caused by a race condition

### PR DESCRIPTION
**Pull request by regevbr**
I noticed that my switches are stuck in an `unavailable` state until I actually use them.
After long debugging, I realized that when the entity is created at boot time, it does not get an update from its device class. The logging clearly showed that the device was created and connected first, got the initial status of the device, and publish the event to the entities, but alas, the entities were not created yet... When they do get created, no one bothers to update their status until the physical device gets updated, rendering them stuck in an `unavailable` state.

I fixed it (and verified it on my HA instance) by making entities publish an event to the device letting them know they were created, so the device class can resend the status update event.

### CODE REVIEW

**Comment by regevbr** [comment]
@rospogrigio can you please CR? this is a major bug fix :-)

**Comment by regevbr** [comment]
hi @rospogrigio did you have a chance to review the changes by any chance?

**Comment by regevbr** [comment]
hi @rospogrigio did you have a chance to review the changes by any chance?

**Comment by rospogrigio** [comment]
Not yet, sorry... will try it now and let you know in a couple of days, thank you for your patience...

**Comment by regevbr** [comment]
Hi @rospogrigio did you have a chance to look it over?

**Comment by rospogrigio** [comment]
Sorry I really hadn't found the time to test it until now.
I have just out this under test on my main HA environment, if I don't see glitches or strange behaviors I'll merge it in a couple of days, ok?
Thank you for your patience

**Comment by regevbr** [comment]
@rospogrigio sounds good thanks!

**Review by rospogrigio — APPROVED** [review]

**Pull request merged**
