### PR TITLE
Zigbee gateway support

### PR DESCRIPTION
**Pull request by sbneto**
I based my work on https://github.com/rospogrigio/localtuya/pull/318 and fast-forwarded to the master branch. I introduced the `client_id` key (which I believe stands for `cid`) to the device configuration like this:

```
localtuya:
  - host: 192.168.1.xxx
    device_id: {device-id}
    local_key: {gateway-local-key}
    client_id: {device-mac-address}
    friendly_name: Gateway
    protocol_version: "3.3"
    entities:
      - platform: switch
        friendly_name: {some-name}
        id: 1
```

and adjusted the payload as suggested here https://github.com/rospogrigio/localtuya/pull/318#issuecomment-870811955.

I managed to get it working, I can turn the lights off and on again on my 4-gang zigbee switch, but sometimes it gets stuck and takes a while to start replying again (I imagine these are related to the timeouts in the comment above). I might be missing something in order to make it more stable, any suggestions are appreciated.

EDIT: I changed the branch to improve on the https://github.com/rospogrigio/localtuya/pull/739 instead of the https://github.com/rospogrigio/localtuya/pull/318, since those are not in the same commit tree anymore.

### CODE REVIEW

**Review by fuatakgun — APPROVED** [review]

**Comment by fuatakgun** [comment]
I confirm that this is also working for bluetooth gateway and devices.
regarding to finding out cid, I used tuya-cli to dump the information

**Comment by leeyuentuen** [comment]
I've tested them, if I have multiple PIR motion sensors, it will update all of them as on if one of them is detected as on

**Comment by knifehandz** [comment]
> I've tested them, if I have multiple PIR motion sensors, it will update all of them as "on" if one of them is detected as on see video below
> 
>  screenrecord.mp4 
> used yaml
> 
> ```
> - host: 172.16.0.60
>     device_id: bfe1f786562ffa1xxxxxnp
>     local_key: 8ade150591c51a76
>     client_id: 00124b000fed9eba
>     friendly_name: "Local Motion Sensor Shower"
>     protocol_version: "3.3"
>     entities:
>       - platform: binary_sensor
>         friendly_name: Local Motion Shower Shower
>         id: 1
>         device_class: motion
>         state_on: "pir" # Optional
>         state_off: "none"
> 
>   - host: 172.16.0.60
>     device_id: bf7f612d6264a450xxxxbd
>     local_key: 8ade150591c51a76
>     client_id: 00124b00128c5753
>     friendly_name: "Local Motion Sensor toilet"
>     protocol_version: "3.3"
>     entities:
>       - platform: binary_sensor
>         friendly_name: Local Motion Sensor toilet
>         id: 1
>         device_class: motion
>         state_on: "pir" # Optional
>         state_off: "none"
> 
>   - host: 172.16.0.60
>     device_id: bf25877e84982d21xxxxk2
>     local_key: 8ade150591c51a76
>     client_id: 00124b0010307c4f
>     friendly_name: "Local Motion Sensor upstairs"
>     protocol_version: "3.3"
>     entities:
>       - platform: binary_sensor
>         friendly_name: Local Motion Sensor upstairs
>         id: 1
>         device_class: motion
>         state_on: "pir" # Optional
>         state_off: "none"
> ```

I too have tested this and got the same results. I have about 13 Tuya Zigbee switches (1, 2, 3, and 4-gang ones) and if I add them with @sbneto 's patch on the same gateway, states are updated across different ones under the same gateway.

Been trying to study the code and made some changes, adding a dictionary for type_0d to GATEWAY_PAYLOAD_DICT, and so far not seeing errors in the log anymore.

What I am unable to understand yet, is the device cache mechanism and the relationship between it and the status updates. It just seems although things are indexed by device ID, they somehow also get updated at the same time if they use the same host address (not sure).

Interestingly, if I add a 1-gang switch and 2-gang switch under the same gateway, dp 1 of 1-gang and dp1 of 2-gang would be updated at the same time; but dp2 of the 2-gang works totally fine.

Given my limited knowledge of how things really work in LocalTuya, may I ask if there's anything I should look to test and change?

PS. Been through official Tuya integration, slow and unreliable at best. Rather jump in and have things working locally (I'm not blocking any Internet access though, my main motivation is not privacy but stability).

Thanks!

**Comment by knifehandz** [comment]
Sorry forgot to say, a sample payload I am getting from a Zigbee switch is:
`2021-12-19 15:42:08 DEBUG (MainThread) [custom_components.localtuya.pytuya] [eb2...2wm] Decrypted payload: {"dps":{"1":true},"cid":"60a423fffe30564a","t":1639903327}`

**Comment by sbneto** [comment]
Hey guys, thanks for the feedback. I have not tried with multiple devices in the same hub indeed, I will add another switch and see how it goes. I was just testing with a single switch since I don't have my final hardware setup done at home yet, but will get things going once all switches are installed.

**Comment by knifehandz** [comment]
Hi @sbneto, if I can be of any help, do let me know. I am not an experienced HA dev, but I do regular development in Python and IoT (ESP) stuff.

Just don't know where to start yet.

**Comment by knifehandz** [comment]
I figured out what is causing this status issue.

A Tuya Zigbee gateway (or hub), from HA's point of view at the moment, is a single Tuya device with one entity, while in reality it has sub-devices. Each sub-device works exactly the same way as a single WiFi device. In other words, they are devices within a device. "cid" is used to distinguish between each sub-device.

When requesting a status update (0x0A) with a cid, the gateway will query that particular sub-device and return its status. If multiple connections are made to the same Zigbee gateway, it will push updates to every connection for _any_ sub-device changes with "cid" specified in the payload.

This is exactly what is causing simultaneous status updates to multiple devices under the same gateway. Each LocalTuya device makes a connection to the gateway, and when something changes under the gateway (PIR or switch as tested so far), it'll push an update to _all_ LocalTuya devices connected to it, with its dps status in the payload.

For example:
- Switch A is a 1-gang Zigbee switch
- Switch B is a 2-gang Zigbee switch
- Switch A and switch B are under the same gateway
- Switch A's first gang gets turned off, this generates a push update like `{"dps":{"1":false},"cid":"xxx","t":xxx}`, which in turn triggers an update to its LocalTuya entity
- Switch B also receives this update, which then also updates its entity accordingly
- Under the hood, the dps_cache in pytuya for both devices are updated

Below are the actual test results captured by isolating pytuya from LocalTuya and running the attached custom test code:
```
1 and Enter to turn on, 0 and Enter to turn off, Enter only to end
[eb2...rif] Connecting to Study Room Switch, ID xxxrif
[eb9...kb0] Connecting to Living Room Switch, ID xxxkb0
[eb2...rif] Sending command status (device type: type_0a)
[eb2...rif] Send payload: b'{"cid":"xxx64a"}'
[eb2...rif] Waiting for sequence number 1
[eb9...kb0] Retrieving initial state
[eb9...kb0] Sending command status (device type: type_0a)
[eb9...kb0] Send payload: b'{"cid":"xxxd40"}'
[eb9...kb0] Waiting for sequence number 1
[eb2...rif] Decrypted payload: {"dps":{"1":true,"14":"memory","15":"pos"},"cid":"xxx64a"}
[eb2...rif] Status updated: {'1': True, '14': 'memory', '15': 'pos'}
[eb9...kb0] Dispatching sequence number 1
[eb9...kb0] Decrypted payload: {"dps":{"1":false,"2":false,"14":"memory","15":"pos"},"cid":"xxxd40"}
[eb9...kb0] Status updated: {'1': False, '2': False, '14': 'memory', '15': 'pos'}
0
[eb2...rif] Sending command set (device type: type_0a)
[eb2...rif] Send payload: b'{"cid":"xxx64a","dps":{"1":false}}'
[eb2...rif] Waiting for sequence number 2
[eb2...rif] Dispatching message TuyaMessage(seqno=2, cmd=7, retcode=0, payload=b'', crc=416269786)
[eb2...rif] Dispatching sequence number 2
[eb2...rif] Decrypted payload: {}
1 and Enter to turn on, 0 and Enter to turn off, Enter only to end
[eb2...rif] Got status update
[eb2...rif] Decrypted payload: {"dps":{"1":false},"cid":"xxx64a","t":1640460792}
[eb2...rif] Status updated: {'1': False, '14': 'memory', '15': 'pos'}
[eb9...kb0] Got status update
[eb9...kb0] Decrypted payload: {"dps":{"1":false},"cid":"xxx64a","t":1640460792}
[eb9...kb0] Status updated: {'1': False, '2': False, '14': 'memory', '15': 'pos'}
1
[eb2...rif] Sending command set (device type: type_0a)
[eb2...rif] Send payload: b'{"cid":"xxx64a","dps":{"1":true}}'
[eb2...rif] Waiting for sequence number 3
[eb2...rif] Dispatching message TuyaMessage(seqno=3, cmd=7, retcode=0, payload=b'', crc=3310951519)
[eb2...rif] Dispatching sequence number 3
[eb2...rif] Decrypted payload: {}
1 and Enter to turn on, 0 and Enter to turn off, Enter only to end
[eb2...rif] Got status update
[eb2...rif] Decrypted payload: {"dps":{"1":true},"cid":"xxx64a","t":1640460794}
[eb2...rif] Status updated: {'1': True, '14': 'memory', '15': 'pos'}
[eb9...kb0] Got status update
[eb9...kb0] Decrypted payload: {"dps":{"1":true},"cid":"xxx64a","t":1640460794}
[eb9...kb0] Status updated: {'1': True, '2': False, '14': 'memory', '15': 'pos'}
```

Thinking about possible solutions:
1. Just use multiple devices and add the ability to filter status updates based on cid - definitely works, but comes with two problems: for my case, there are some gateways handling 7-10 sub-devices. This will cause a lot of heartbeats, push updates, and I am not too sure if the gateway itself can handle this kind of load
2. Add the ability for LocalTuya to handle sub-devices - this should be the ideal solution, but requires many changes to pytuya and LocalTuyaDevice / LocalTuyaEntity

For solution 2, the tasks to be done are:

- Modify pytuya to be able to handle multiple cids under the same connection
- Modify LocalTuya to be able to handle sub-devices as entities and use cid to distinguish them
- Modify flow config to be able to add sub-devices if it's a Zigbee gateway

I am about 30% done with solution 2, but doing it without discussing first because I really need to be able to automate stuff. Would like to ask if there are better ways to do this, as I am not really experienced with HA development.

[pytuya_test.zip](https://github.com/rospogrigio/localtuya/files/7776233/pytuya_test.zip)

**Comment by leeyuentuen** [comment]
i've done here a change, it seems to be work?
https://github.com/rospogrigio/localtuya/pull/735

**Comment by knifehandz** [comment]
Hi @sbneto, can I invite you to help to test out the implementation @leeyuentuen and I worked out together on #739? It's based on your work with a different approach.

**Comment by sbneto** [comment]
@knifehandz Thanks a lot for continuing where I left off. I did not have time to check back on this since the beginning of the year, but I think I managed to get a version of this working with `v4`. I kept working from your branch so that we can keep the commit history. I understood what you did, but I think there might be a simpler way to associate a device with the subdevices other than re-implementing the `TuyaDevice` object twice. The way I made it work for the time being is by filtering on the `cid`, but as you mentined, this increases the network burden. I will try to get the subdevices approach built into the `TuyaDevice`, but in a slightly different way, as soon as I have the time. For now, I just wanted to get my switch working again. I am also opening a PR to your project in case you want to sync our branches, if you accept that I believe I can close this one and we can concentrate the work there.

@rospogrigio amazing work with `v4`, congratulations and thanks a lot! It is so much better to have the plugin querying the API, setup is trivial now.

As things stand, I belive setting a gateway device is as straight forward as adding any other device once you have your Tuya api credentials setup. It will discover and auto-populate the fields, and you will just have to give each dp a nice name.

@fuatakgun Plz take another pass on this if you have the time.

**Comment by rospogrigio** [comment]
Great job @sbneto , that last commit is a good optimization. I'm merging it in #898 , thank you!

**Comment by knifehandz** [comment]
@sbneto Happy that you are back! I too have had little time to check back for 2 months now. Having looked at your PR I think it's excellent and will get it merged soon.

Initially, I just wanted to get Zigbee switches in my house to work so I could automate them, but little did I realize why these are called "gateways" is because they act like one (to be honest I once thought they have an API or something, somewhat smart about what they get and what they do). Hopefully in the end things will work with the awesome v4 update flawlessly.

Please do assume a scenario of a Zigbee gateway with 10 attached devices (switches, PIR, etc.) and each device with 3 buttons, which is why I came up with the solution to have only one connection to the gateway network-wise and to have subdevices to communicate through it.

A network burden is the least of worry to me, as these messages will probably make at most 1 Kbps traffic for a second.

What worried me was the number of exchanges that must happen between LocalTuya and the gateway. If every single subdevice requires a connection to be established to the gateway, that's 10 connections; and for each of these connections, each subdevice update will generate an update to LocalTyua. Just turning on a button on one switch, and off on another switch (2 actions), will generate 20 status updates on the side of the gateway, which I am not too sure if these gateways can or are supposed to handle, less other resource concerns.

After merging your PR, I'll be sure to check back at least twice a week to make sure I don't miss anything. Thank you again for coming back and for the hard work of getting it to work with `v4` :)

**Comment by sbneto** [comment]
Closing in favor of https://github.com/rospogrigio/localtuya/pull/739

**Pull request closed without merging**
