### PR TITLE
Adding Number and Select platforms

### PR DESCRIPTION
**Pull request by sibowler**
Added Number and Select platforms as entity types. Allows support for a winder range of devices.

I introduced to add support for a Security Light which has a mode controlled by strings (mode_on/mode_off/mode_auto) and with other settings controlled by numbers. However the implementations are generic, so hoping these are of use to others.

### CODE REVIEW

**Comment by sibowler** [comment]
Hi @rospogrigio - have updated the files - hopefully they pass all checks now.

**Comment by sibowler** [comment]
Hi @rospogrigio - apologies for that last one - thought i had fixed the errors, but was working off the github tox output. Have now done it properly, installed tox/black and worked through the errors. Hoping this should all be sweet now.

**Comment by sibowler** [comment]
@rospogrigio - Any idea on the tox _homeassistant.components.select_ import error? It's the right reference according to https://developers.home-assistant.io/docs/core/entity/select/, not to mention it works correctly in HA?

**Comment by rospogrigio** [comment]
You are getting an error from black, run `black --fast *.py` to reformat the code and commit again...

**Comment by sibowler** [comment]
OK thanks - I'd missed that change, I thought the other errors were the issue. Re-ran now and checked in file.

**Comment by sibowler** [comment]
Hi @rospogrigio - all the style issues seem to have been resolved. I had to increase the version dependency for home assistant to the July 2021 release (and the crypto libraries), as the SelectEntity wasn't in the Jan 2021 HA version that was previously referred to.

**Comment by rospogrigio** [comment]
OK it's not much clear to me what this PR is for exactly, can you explain it to me please?

**Comment by sibowler** [comment]
Yep, certainly.

It adds two new entity types:

1. A select (drop-down entity), which is useful for Tuya devices with DPS that can take an enumeration of values... i.e. on/off/restore. The SelectEntity I've defined also optionally allows a separation of user friendly and the actual device values. As an example, you could show On/Off/Previous power state as the options to the user, but send through on/off/restore as the actual values to the device.
2. A number entity type, that allows for a DPS that takes a number as an input value. It allows setting of the minimum/maximum values.

These are mainly useful where a device's settings don't fit neatly into one of the other platforms (light/fan/switch/...).

Does that help? Otherwise I'm happy to provide some more examples of use if that would be useful?

**Comment by rospogrigio** [comment]
OK now I see. Yes, I believe it can be helpful for certain entity types such as climates and vacuums.
OK thank you

**Review by rospogrigio — APPROVED** [review]

**Pull request merged**
