### PR TITLE
Fix for connection errors for certain devices

### PR DESCRIPTION
**Pull request by sibowler**
Fixes the AttributeError: 'TuyaMessage' object has no attribute 'release' error observed in Issue #1017 .

So far untested as I don't have devices which exhibit this behavior, but seems to be caused by duplicate responses coming through, without a corresponding request. Should gracefully handle this situation now. Additional debug logging has been handled to identify when this issue occurs.

### CODE REVIEW

**Comment by AFumi39** [comment]
I'm trying this fix, for now I see this (that before never showed) in the Logs:

```
Logger: custom_components.localtuya.switch
Source: custom_components/localtuya/pytuya/__init__.py:150
Integration: LocalTuya ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: 10:47:59 (12 occurrences)
Last logged: 10:49:11

[121...c05] Entity switch.dyson is requesting unknown DPS index 1
```

I didn't set any DPS in device configuration

**Comment by sibowler** [comment]
@AFumi39 That error occurs further up the stack than this change. Can you check if the switch entity for your dyson is assigned to DPS 1? 

The other thing to try (and I acknowledge this might be a bit of a pain) is to try recreating that device and see if the error persists?

**Comment by AFumi39** [comment]
> @AFumi39 That error occurs further up the stack than this change. Can you check if the switch entity for your dyson is assigned to DPS 1?
> 
> The other thing to try (and I acknowledge this might be a bit of a pain) is to try recreating that device and see if the error persists?

I've never seen it before the change, so I just thought that maybe before it wasn't logged correctly, and with your fix is now shown.
But it seems that is completely unrelated, because it occurred 647 times until 12:23:01, than no more errors ant the device started working correctly in HA.

I checked and the entity is assigned to DPS 1, so I really don't know what happened...

**Review by laithsaid — APPROVED** [review]

**Comment by AFumi39** [comment]
The problem is not completely resolved (but better than before, 'cause now some devices goes offline, but not ALL).
See here: https://github.com/rospogrigio/localtuya/issues/1077#issuecomment-1284255456

**Comment by sibowler** [comment]
@AFumi39 - do you have logs for those devices that aren't working correctly?

**Comment by AFumi39** [comment]
> @AFumi39 - do you have logs for those devices that aren't working correctly?

Unfortunately I forgot to save the log before the restart...
Next time it happens I'll post it

**Comment by AFumi39** [comment]
There error is this:
```
Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:707
Integration: LocalTuya ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: 19 ottobre 2022 18:03:46 (11 occurrences)
Last logged: 04:11:08

[bf9...6qh] Connect to 192.168.1.26 failed
[121...863] Connect to 192.168.1.242 failed
[734...1f1] Connect to 192.168.1.87 failed
[121...9d2] Connect to 192.168.1.61 failed
[121...c3c] Connect to 192.168.1.215 failed
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 186, in _make_connection
    self._interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 707, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionResetError: [Errno 104] Connect call failed ('192.168.1.242', 6668)
```
Sometimes it "recover" automatically (after some time it work again), but I think that if the error goes on for too much time, HA deny LocalTuya from further attempts and the devices remain offline.

**Comment by AFumi39** [comment]
With no specific log in the system logs (apart from the error just posted yesterday in the previous message), I just noticed that last night all the light-type devices gone offline (all the other devices are still online).
Don't know why, but with the official (cloud) Tuya integration it's all ok.

**Comment by sibowler** [comment]
> There error is this:
> 
> ```
> Logger: custom_components.localtuya.common
> Source: custom_components/localtuya/pytuya/__init__.py:707
> Integration: LocalTuya ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
> First occurred: 19 ottobre 2022 18:03:46 (11 occurrences)
> Last logged: 04:11:08
> 
> [bf9...6qh] Connect to 192.168.1.26 failed
> [121...863] Connect to 192.168.1.242 failed
> [734...1f1] Connect to 192.168.1.87 failed
> [121...9d2] Connect to 192.168.1.61 failed
> [121...c3c] Connect to 192.168.1.215 failed
> Traceback (most recent call last):
>   File "/config/custom_components/localtuya/common.py", line 186, in _make_connection
>     self._interface = await pytuya.connect(
>   File "/config/custom_components/localtuya/pytuya/__init__.py", line 707, in connect
>     _, protocol = await loop.create_connection(
>   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
>     raise exceptions[0]
>   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
>     sock = await self._connect_sock(
>   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
>     await self.sock_connect(sock, address)
>   File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
>     return await fut
>   File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
>     raise OSError(err, f'Connect call failed {address}')
> ConnectionResetError: [Errno 104] Connect call failed ('192.168.1.242', 6668)
> ```
> 
> Sometimes it "recover" automatically (after some time it work again), but I think that if the error goes on for too much time, HA deny LocalTuya from further attempts and the devices remain offline.

That error shows that localtuya can't connect to the device for some reason - but there's nothing in the error that helps narrow down why it can't connect to that device. Can you try turning up your logging for localtuya? To do this add the following lines to your configuration.yaml file (not if you've already got a logger: logs: section in that file, you will only need the last 2 lines):

```
logger:
  default: warning
  logs:
    custom_components.localtuya.pytuya: debug
    custom_components.localtuya: debug
```



> With no specific log in the system logs (apart from the error just posted yesterday in the previous message), I just noticed that last night all the light-type devices gone offline (all the other devices are still online). Don't know why, but with the official (cloud) Tuya integration it's all ok.

The official Tuya integration is a completely different method of connecting - But i think given you've confirmed that the connectivity is there through that integration, it would be worthwhile disabling these problematic devices in that integration, whilst you debug this issue. Just to rule out any interference caused by those comms.

**Comment by AFumi39** [comment]
This morning, between about 07:50-08:20, 3 devices gone offline in LT.
The errors I see on the log registry those two:
`Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: homeassistant
Source: custom_components/localtuya/discovery.py:67
Integration: LocalTuya (documentation, issues)
First occurred: 25 ottobre 2022 18:22:52 (24 occurrences)
Last logged: 06:19:20

Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/config/custom_components/localtuya/discovery.py", line 65, in datagram_received
    data = decrypt_udp(data)
  File "/config/custom_components/localtuya/discovery.py", line 30, in decrypt_udp
    return _unpad(decryptor.update(message) + decryptor.finalize()).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 12: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 1027, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/config/custom_components/localtuya/discovery.py", line 67, in datagram_received
    data = data.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 4: invalid start byte
`

`Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:707
Integration: LocalTuya (documentation, issues)
First occurred: 25 ottobre 2022 15:43:11 (19 occurrences)
Last logged: 04:11:05

[bf8...ae3] Connect to 192.168.1.222 failed
[121...c05] Connect to 192.168.1.204 failed
[121...863] Connect to 192.168.1.242 failed
[734...1f1] Connect to 192.168.1.87 failed
[010...1ef] Connect to 192.168.1.107 failed
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 186, in _make_connection
    self._interface = await pytuya.connect(
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 707, in connect
    _, protocol = await loop.create_connection(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionResetError: [Errno 104] Connect call failed ('192.168.1.107', 6668)
`

**Comment by AFumi39** [comment]
The problem persists, with only these two errors

**Comment by AFumi39** [comment]
Ok, now I have the problem again with 1 device only, bit no LocalTuya error is visible on the system log.
I have these errors that appear in the same minute the device became unavailable (none of them is about the LT device):

```
Logger: pychromecast.socket_client
Source: /usr/local/lib/python3.10/site-packages/pychromecast/socket_client.py:672
First occurred: 29 ottobre 2022 14:02:51 (13 occurrences)
Last logged: 16:51:23

[Orologio Andrea(192.168.1.64):8009] Heartbeat timeout, resetting connection
[TV del salotto(192.168.1.246):8009] Heartbeat timeout, resetting connection
[Camera da letto(192.168.1.82):8009] Heartbeat timeout, resetting connection
[Soggiorno(192.168.1.208):8009] Heartbeat timeout, resetting connection
```

```
Logger: homeassistant.components.xiaomi_miio
Source: helpers/update_coordinator.py:151
Integration: Xiaomi Miio (documentation, issues)
First occurred: 29 ottobre 2022 18:47:13 (5 occurrences)
Last logged: 16:51:38

Timeout fetching zhimi.airpurifier.mb3 data
```

```
Logger: homeassistant.helpers.template_entity
Source: helpers/template_entity.py:321
First occurred: 29 ottobre 2022 11:15:39 (20 occurrences)
Last logged: 16:51:38

TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ (states("sensor.consumo_contatore_totale") | float) | round(2) }}' but no default was specified') while processing template 'Template("{{ (states("sensor.consumo_contatore_totale") | float) | round(2) }}")' for attribute '_attr_native_value' in entity 'sensor.house_electricity_energy'
TemplateError('ValueError: Template error: int got invalid input 'None' when rendering template '" {% macro phrase(value, name) %} {%- set value = value | int %} {%- set end = 's' if value > 1 else '' %} {{- '{} {}{}'.format(value, name, end) if value | int > 0 else '' }} {%- endmacro %} {% set weeks = (state_attr('fan.zhimi_airpurifier_mb3', 'use_time') | int / 604800) | int %} {% set days = ((state_attr('fan.zhimi_airpurifier_mb3', 'use_time') | int - (weeks * 604800)) / 86400) | int %} {% set hours = ((state_attr('fan.zhimi_airpurifier_mb3', 'use_time') | int - (weeks * 604800) - (days * 86400)) / 3600) | int %} {% set minutes = ((state_attr('fan.zhimi_airpurifier_mb3', 'use_time') | int - (weeks * 604800) - (days * 86400) - (hours * 3600)) / 60) | int %} {% set seconds = (state_attr('fan.zhimi_airpurifier_mb3', 'use_time') | int - (weeks * 604800) - (days * 86400) - (hours * 3600) - (minutes*60)) | int %} {{ [ phrase(weeks, 'week'), phrase(days, 'day'), phrase(hours, 'hr'), phrase(minutes, 'min'), phrase(seconds, 'sec') ] | select('!=','') | list | join(', ') }}"' but no default was specified') while processing template 'Template("" {% macro phrase(value, name) %} {%- set value = value | int %} {%- set end = 's' if value > 1 else '' %} {{- '{} {}{}'.format(value, name, end) if value | int > 0 else '' }} {%- endmacro %} {% set weeks = (state_attr('fan.zhimi_airpurifier_mb3', 'use_time') | int / 604800) | int %} {% set days = ((state_attr('fan.zhimi_airpurifier_mb3', 'use_time') | int - (weeks * 604800)) / 86400) | int %} {% set hours = ((state_attr('fan.zhimi_airpurifier_mb3', 'use_time') | int - (weeks * 604800) - (days * 86400)) / 3600) | int %} {% set minutes = ((state_attr('fan.zhimi_airpurifier_mb3', 'use_time') | int - (weeks * 604800) - (days * 86400) - (hours * 3600)) / 60) | int %} {% set seconds = (state_attr('fan.zhimi_airpurifier_mb3', 'use_time') | int - (weeks * 604800) - (days * 86400) - (hours * 3600) - (minutes*60)) | int %} {{ [ phrase(weeks, 'week'), phrase(days, 'day'), phrase(hours, 'hr'), phrase(minutes, 'min'), phrase(seconds, 'sec') ] | select('!=','') | list | join(', ') }}"")' for attribute '_attr_native_value' in entity 'sensor.mi_air_purifier_use_time'
```

**Comment by sibowler** [comment]
Hi @AFumi39 - Unfortunately I'd say this looks like a different type of error. The errors are during the connection procedure and seem to be either a) not being able to reach the device/get any response or b) when a response is received it is not within the expected format. As this particular change relates to neither of these two areas, can I get you to raise this as a separate issue?

In regards to the device which started working again, did you change anything (i.e power cycle the device, change the wifi network coverage/location of the device)?

**Comment by nzrutman** [comment]
Experiencing same problem. Will try the patch here with debug logging. Another possible clue is that other integrations sometimes also report connection-type errors around the same time. Possibly intermittent network outage results in lost messages, and localtuya doesn't recover?
 
```
2022-10-29 15:04:10.846 ERROR (MainThread) [custom_components.localtuya.common] [704...314] Connect to 192.168.86.22 failed
Traceback (most recent call last):
  File "/Users/nathan/.homeassistant/custom_components/localtuya/common.py", line 186, in _make_connection
    self._interface = await pytuya.connect(
  File "/Users/nathan/.homeassistant/custom_components/localtuya/pytuya/__init__.py", line 704, in connect
    _, protocol = await loop.create_connection(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1055, in create_connection
    raise exceptions[0]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1040, in create_connection
    sock = await self._connect_sock(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 954, in _connect_sock
    await self.sock_connect(sock, address)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 507, in _sock_connect
    sock.connect(address)
OSError: [Errno 64] Host is down
```

**Comment by sibowler** [comment]
@rospogrigio - What do you want to do with this PR? I've got some other changes to go in to fix the RESET behaviour for some devices, but wanted to know if this code is going to be part of that baseline, or not?

Also getting some weird TOX validation failure for the python 3.7 checks. Any ideas there? I can't seem to replicate on my system.

**Comment by rospogrigio** [comment]
OK this change seems reasonable but I have to investigate it, I would like to understand more clearly the problem (didn't notice this PR).
I also have found a couple of fixes for situations in which devices would get a temporary disconnection and would not try to reconnect.
My idea is to include this fix too and come up within a week or two with a "stability PR" for everybody to test to check if we got rid of the main disconnection issues.
What other changes do you have in mind?

**Comment by rospogrigio** [comment]
> Also getting some weird TOX validation failure for the python 3.7 checks. Any ideas there? I can't seem to replicate on my system.

Yeah I am pissed off too by those checks and I have tried to modify them with no luck. If anybody can help I'd be grateful, I don't understand where they are supposed to be tweaked...

**Comment by sibowler** [comment]
> OK this change seems reasonable but I have to investigate it, I would like to understand more clearly the problem (didn't notice this PR). I also have found a couple of fixes for situations in which devices would get a temporary disconnection and would not try to reconnect. My idea is to include this fix too and come up within a week or two with a "stability PR" for everybody to test to check if we got rid of the main disconnection issues. What other changes do you have in mind?

I think that sounds reasonable to bundle them. This particular change is one that I haven't observed in my environment, but others above had. My perspective is that it's just cleaner error handling for this situation.

The RESET issue was caused by the changes I made to make the RESET command only be called when configured. Unfortunately I made it so that it was only called if no DPS were detected. However, some devices will publish a primary DPS, but the RESET command is required to enable the other DPS - Currently, the RESET command will not be fired in this situation. So the fix I have addresses this.

**Comment by sibowler** [comment]
I could make the RESET changes on this branch, or I can separate them out. What do you think?

**Comment by rospogrigio** [comment]
Maybe it's better to keep them in separate PRs, so it's easier to track them down..

**Comment by sibowler** [comment]
No worries - I've done that. Only thing holding me back from raising a PR
is that I haven't tested the RESET fix in isolation of this change. I'm
currently away on holiday, but will be back in a week, so will test then
and assuming all good, will raise the
PR.

Then once all these fixes are through, I plan to work on making the Light
entity work with passive devices.

**Comment by sibowler** [comment]
@rospogrigio - I think I've got a lead on the tox issue. Under .github/workflows there is the tox.yaml file. In there it lists python3.7 & python 3.8 which is out of line with the tox.ini file. I think all that needs to be done is to remove the python 3.7 line (and potentially add the python 3.9 line).

**Pull request merged**
