### PR TITLE
Vacuum platform new

### PR DESCRIPTION
**Pull request by rikman122**
Introduced updated vacuum platform.

### CODE REVIEW

**Comment by rikman122** [comment]
Initial approach of the Tuya Custom Card can be found here: [Tuya Vacuum Card](https://github.com/rikman122/tuya-vacuum-card)

**Comment by remb0** [comment]
I hope that I can test it soon when it's merged

**Comment by timota** [comment]
Straight away comment regarding `pause`. 
You are using common management `dp` (in your case 27), and mode `standby`. So behaviour (in my case) - robot paused, do not returned to base but program resets, which is incorrect. Most vacuums has option play/pause. In my case `dp=2 {True/False}` (also, this dp shows working state) in this case - robot do real pause and didn't reset program so you can unpause it and it will continue. So i advise to add separate `dp` option to play/pause. 
I dont know if you see this [Standard Instruction Set](https://developer.tuya.com/en/docs/iot/fsd?id=K9gf487ck1tlo), but it describes most options, unfortunately no `dp`s. 

Regarding my specific case - can you add please options for `mopping` mode. It one of cleaning modes, but when it selected i have additional option `Water control ` - "low, normal, hight". 

Sorry im not a python dev, so for me it a bit harder to write code as you did, but if you need any kind of help in testing/developing - le me know. 

Regards.

**Comment by rikman122** [comment]
Hi @timota!

Thank you for your information. I saw the Standard Instruction Set but unfortunately looks like each vacuum is different and in my case, most of the functions described there didn't match my vacuum so I think it's a better approach to let people test this and share what they find out in order to improve the component.

You are right with the pause behaviour, in my case it's DP 25 which I totally forget about. I'm currently fixing this right now.

For the mopping, my vacuum doesn't have this option so I can't test it. If you want, we can have a chat on Discord or somewhere and try to find out the way to add this functionallity.

Again, thank you for the support!!

**Comment by timota** [comment]
Sorry for late response, was busy with a kids. 

Sure we can talk in discord. My id: `timota#4996`. 

PS: trying your branch now, and looks like i did misconfiguration or found a bug. Dont know what is exactly.  Will be more than happy to discuss it with you.
Regards.

**Comment by timota** [comment]
also, found that it will more reasonable to split `modes` on 2 config attrs, like `contol_modes` and `cleaning_modes`. 
```yaml
commands_set: "smart,standby,chargego"
cleaning_modes: "smart,wall_follow,spiral,partial_bow"
```
at least it will be easier to show modes in your lovelace card. Currently it contains all modes, but, lets say `chargego` that currently defined in `modes` should not be there. For those modes `gohome, chargego, start, stop` vacuum integration already defined services that can be called directly. 

Hope this makes sense.

**Comment by timota** [comment]
@rikman122 i've made some changes to your original PR to support 'Paused' mode, but unfortunately can not commit to your PR as it closed for me. Can you give me permissions please. Or reach me out via discord. 

Regards

**Comment by rikman122** [comment]
Hi @timota,

Thank you for the feedback! I can only dedicate my free time on this so I'm only available on weekends but everything you said about modes makes sense.

For the paused thing It should work with my last commit. I tested it on my vacuum and now it pause/resume without stopping the program.

For the lovelace card, as I said, I'm not a frontend developer so I did the card with the basic functionality. Feel free to modify it as any improvement is well accepted.

I'll add you to Discord so we discuss other details.

Regards

**Comment by timota** [comment]
Hi @rikman122, 

regarding play/pause you did great job. What i have added - that when robot in paused state - in card you can see that it paused. 

```python
        elif state_value == self._config[CONF_RETURNING_STATUS_VALUE]:
            self._state = STATE_RETURNING
        elif state_value == self._config[CONF_PAUSED_STATE]:
            self._state = STATE_PAUSED
```

and couple more bits, so HA can handle it state correctly. If you can give me permissions to push to your repo (PR) it will be great, so dont need to waste your and my time. Easier to work together. 

BTW: Thank you that you've added me to discord. 

Regards.

**Comment by saltabas** [comment]
Sorry for this newbie question. I own a "Honiture Q6" Tuya based vacuum. I'm trying to test integration but the dp list on config seems totally different. Here a couple of examples:
101 power
102 power go
103 in dock station
104 mode
105 state
106 battery
107 last session time
108 last session area
116 total time
117 total area
118 total sessions
122 error codes
137 carpet boost
138 mop
How can I proceed?
Regards

**Comment by rikman122** [comment]
Hi @saltabas,

Just set the DPs corresponding to your vacuum. Note that not all the functions are supported at this moment so just set the DPs that match each of the supported functions.

For the modes list, fan speeds and other related states you have to find out which are the defined names for your vacuum. You can take a look at the "Get the instruction set supported by the device" section in the [API Explorer](https://iot.tuya.com/cloud/explorer) of the Tuya IoT Platform.

**Comment by martimarkov** [comment]
@rospogrigio What is blocking this PR from being merged? Anything we can do to get it in mainland?

**Comment by rospogrigio** [comment]
Sorry didn't notice this. Looks like it's good, are there any feedbacks reporting that it works correctly? I don't have a vacuum device to test this.

**Comment by rikman122** [comment]
Hey @rospogrigio
Could you please run the test again? It should pass them now.

Thank you

**Comment by rikman122** [comment]
Hi @rospogrigio 

I'm not sure why is failling tests now. Could you please check it as I'm not familiar with tox?.

Thank you

**Comment by rospogrigio** [comment]
@rikman122 you should run flake8 and black --fast before pushing and see if they are reporting errors, and correct them in case.

**Comment by APayerl** [comment]
@rikman122 When I did a online conversion to black (I have nothing installed on my pc) I got this result:
https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4CINB3xdAD2IimZxl1N_Wk8FsHfswIFI9H9jT9XL2x6wJRx8njVEYxDEdIKjPCAMlCpo-84u5DbsXIzhSNSgxmo_VXyzc6osSFQ3ucQYgs2otLEN-sIMzgaZ518DQj-qhcCZPY3rHy8KLvT9i64Idh6XzDpaBBCycBlbHkU2lKOKn8WzTiHGDO2BZBTwJflz4SXWzH7egW9W8TMgCP4XTgk4Le4E5bDxHe6B8HM7rbRC-NOc4miFXcb_Gidg9piQSUq0V5QkpScQ6UjwjLpONYYLx-8B6NDV-slkiPGsMDpLd0eaz1klM17ovPz4ZF6l3LA3M71x8aPYMTBrvUalK6kYa87ac5Xb1MD9KHW5HPqza10TADAG67_rdB0acMBEk3Tnhe0sA0xPdsw2d3sYT6ad8uXzfNgytXaUA9oKNUJ_Aw9cPRyhe3lxLlSZgBMteQnt6NDlhb8vn03glRepaq0UCBsQ11g7cxc8r8PYHl7LgNnAYe8_YQK9a0iaL8eFLoO1ZUl61NR00obDg5wL1rXJGY-oXZ0910Q7R5pIWFbvjwNCpbzDI9zdesdc7GKNqXpWvU0yaR7Q2S0mrGznD8cXECOF9-pNPkdBJ-DJEUkgMyMm0q2ixymgcuRzeb1rNMYmOVCzaXPKM3SsBbYIEDHabOa3m-RdOvC3qrnzxr0B2oKPJ_OaqEYL5netHBafFzfBemO4xy9zV2Oa40eNIita0Gxw5EuTY1LQ4KI1wzJexXJZ2Hc9TX4DfQ_YJl_TKzmjXMV3ieoVWDxl8aAplbO5w9Gu-gQ_kk13XrdrvC_-PFT0K16qUK8YFkKSspMd4ArtuA3xXiqqnC9mJ94-nvyMtN14DTQNJPWwhUZyeKUTp-kEY3K_92UaotCm_8uOpgWuPb8vj1dNyjiSmLU-GDOhAOun4gagFECjtIS3rOHDi_KFt6sLXZRToNs2UTmVu_FwywwAEMT4RslU02XDt4RLbbGv09HB1YAkSx63dZkruePjSn8WM0MPiz0gCR2Ejvu3U66nYG8jbqRX0rKELgp8fepv-kQj0V7z5Dd7iTq03aG6z-yL2GgzuDDfJOpInQ5deGb5r6BW5EKstE8iJEqwQFkIapMzhu3GnMX-d3nrb6Jp0G-Ufc2lW7P6XD_lK4SaMv01zRcm1LSWcYt28jBwWlTMz96hpabIIY6qrK1GQLItaEaLRf68Qv2Ajz-xNiUXLy51_aD3DkL04-jj7MXrChI6glslDah43LR_vY8-yDj6BLKb6qREfsGBFbO9q-trjLJIMPogqSEGDVArg8S4M0wYvmEiEvt3xwIrEA_DBDMXGLUv4wzlT1YG13sAOfrepF1TjA3hFBVUkWW8jK4bx0KkbMIUIfCN1WFhQddy533zIIQPDqFqg9sLjXSPdd-7nsrarNqkJUbPYmOAOqmg85qSxufUbtfoY8eiGYjgP5kR5jdURX2S5cFstEVHRbt_MC4Uo5mplEginYBEusWTstch8fyPJsF4AAy0rLJ0VPN4DuNK_yT6dCC7ruBms43uc2UZ4uJYkIHY-6sWrAgrfweEo0rDg5x_ZObfu2lrLn-IiRiVFEi6XPgwqtGL8kt4Bh7bGpyz4kVpO78q1szvsCrR5mKiv00hNQ0kNBIY_dX4haVlbHTSG6zaEaKabPVNJyC05tRJn-mjVpZOVVaVXSCeR3Cl7WDbZwFymJu6H4mGbMpIV9HXqEbPzCXY9aCCimZUU4cPHuPqbLH19SP1A4-meHDW57wq03MzgRUONZdDQCQTq6Tir87MX5MUrEwZpyedkFKVmRdvfMOobVr_Gk3zBfrkp4UBEkK5zsIJ7GfAaI2vieUtS-qeQtUgtHUkpIDmek8nwjrna2PYVxOFiLSTkkV--L9XuhGVIxndgGULcQHaG1rIykh_3hcCKXkdgFHFC5xw8USGU6wqNBPLcZnKXVWcxnhafq0LShs4SrX8vl7kFQwnXtdzC9pIg4dwIsPw6XKOyTp-5lndjK_m0gwLssmi6p0L4qWQp4H6CFC3aQq-8dS73a3rCdGFnq-xPmKjRSRXJB83a71iO69SEW3sQ6-dIQz_kgWBefw-pHhsRh6V7bfJ2SZYz5whc-aifQBpQ9EmEipxfLGVAe-9t-2coHMGl_WR-LRiZSVFM3eEjyzJnr4uw7iV5UdhR3SsGTj8S-mHccjYE3YD2hPErnNtcDi5jB8ZPeojJBCGq_OO6lxaLPWdmXr3kMybkYWuVs7ODmOvLg30uH988eibJJIQwPQhIknq5i5YgYTfXmt3HV1KV6H2FnSNfiFdj3Nc3rJEtMONlfKLsuP1FWjfvg0c90SwD7ITHS6LnyG966KfcVjLQW2eD8GCQuosw9qicvcGsyBLaNmmzKKVnmk8b3DQF2DnsYHC-zRjC18t7O1NhnPcN0Dy7-DD6I-J-6D1fGoS8g6iFi8TNW2jRujKqUhAzQZmLGiguNZeBJyREau_uORBFbYmKPt8bhmKqhAFIzmekCoXlks_JloSC146RVhb33jFla9GxEukE6_O0UxhWbQLJKDjGHjcNe53rHMAAJ5ItFKj_VhSAAGYD45EAAA2MyXKscRn-wIAAAAABFla

And then I pasted your original vacuume file into the left box of https://www.diffchecker.com/diff and the black converted one into the right box. This gave a clear overview of the differences!
Found 6-7 differences I think it was, one of which looked like this:
image

**Comment by rikman122** [comment]
Thank you @rospogrigio and @APayerl ! Should be ok now

**Review by APayerl — APPROVED** [review]

**Comment by APayerl** [comment]
@rospogrigio Can we get a review of this again so the automated tests will kick start? 😀

**Review by sthales — APPROVED** [review]

**Comment by sthales** [comment]
Actions works, but state always shows cleaning.
image

Device:

{
  "result": {
    "devices": [
      {
        "active_time": -,
        "biz_type": 0,
        "category": "sd",
        "create_time": -,
        "icon": "-",
        "id": "-",
        "ip": "-",
        "lat": "0.0000",
        "local_key": "-",
        "lon": "0.0000",
        "model": "XR011R",
        "name": "Aécio",
        "online": true,
        "owner_id": "-",
        "product_id": "-",
        "product_name": "KaBuM!Robô aspirador de pó",
        "status": [
          {
            "code": "power",
            "value": true
          },
          {
            "code": "fault",
            "value": 0
          },
          {
            "code": "electricity_left",
            "value": 100
          },
          {
            "code": "power_go",
            "value": false
          },
          {
            "code": "direction_control",
            "value": "foward"
          },
          {
            "code": "mode",
            "value": "standby"
          },
          {
            "code": "status",
            "value": "chargecompleted"
          },
          {
            "code": "suction",
            "value": "normal"
          },
          {
            "code": "voice_switch",
            "value": false
          },
          {
            "code": "clean_area",
            "value": 0
          },
          {
            "code": "clean_time",
            "value": 0
          },
          {
            "code": "clean_record",
            "value": "00000000018"
          }
        ],
        "sub": false,
        "time_zone": "-03:00",
        "uid": "-",
        "update_time": -,
        "uuid": "-"
      }
    ],
    "has_more": false,
    "last_row_key": "-",
    "total": 1
  },
  "success": true,
  "t": -
}

**Comment by sthales** [comment]
Found the issue, had to set id to 28 when adding the device.
Works like a charm. No issues so far.

image

**Comment by rikman122** [comment]
Hi @APayerl 

Yes, the vacuum should be accessible from your HA instance. It should work like every other component in LocalTuya as the vacuum is not responsible of managing devices communications.

**Comment by APayerl** [comment]
okay I think you misunderstood me, HA is able to contact the vacume but thay are not on the same subnet. Does the vacume do multicasts or other things that won't traverse subnets?

**Comment by rikman122** [comment]
Sorry I don't know how the connections are made within LocalTuya and I don't think this is something related with this particular PR but with LocalTuya itself

**Comment by rikman122** [comment]
Hi @rospogrigio 

Can we get a review on this?

**Comment by rikman122** [comment]
Sorry @rospogrigio there was a lint style error. Could you please run it again?

Thank you

**Comment by rikman122** [comment]
Hi again @rospogrigio 

In think this is now ready to be merged

Thank you

**Review by rospogrigio — APPROVED** [review]

**Comment by APayerl** [comment]
Sorry to revive an old PR, but when you have the "Device specification Attribute" object, what is needed to add a vacuum?

I am still struggling, since this is the info for my vacuum:
```
{
  "result": {
    "category": "sd",
    "functions": [
      {
        "code": "power",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "power_go",
        "dp_id": 2,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "dp_id": 3,
        "type": "Enum",
        "values": "{
			"range":[
				"standby",
				"random",
				"smart",
				"wall_follow",
				"mop",
				"spiral",
				"left_spiral",
				"right_spiral",
				"right_bow",
				"left_bow",
				"partial_bow",
				"chargego"
			]
		}"
      },
      {
        "code": "seek",
        "dp_id": 13,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "reset_map",
        "dp_id": 129,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "device_info",
        "dp_id": 132,
        "type": "Raw",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "power",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "power_go",
        "dp_id": 2,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "mode",
        "dp_id": 3,
        "type": "Enum",
        "values": "{
			"range":[
				"standby",
				"random",
				"smart",
				"wall_follow",
				"mop",
				"spiral",
				"left_spiral",
				"right_spiral",
				"right_bow",
				"left_bow",
				"partial_bow",
				"chargego"
			]
		}"
      },
      {
        "code": "seek",
        "dp_id": 13,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "total_clean_time",
        "dp_id": 116,
        "type": "Integer",
        "values": "{
			"unit":"",
			"min":0,
			"max":2147483647,
			"scale":0,
			"step":1
		}"
      },
      {
        "code": "total_clean_area",
        "dp_id": 117,
        "type": "Integer",
        "values": "{
			"unit":"",
			"min":0,
			"max":2147483647,
			"scale":0,
			"step":1
		}"
      },
      {
        "code": "clean_count",
        "dp_id": 118,
        "type": "Integer",
        "values": "{
			"unit":"",
			"min":0,
			"max":2147483647,
			"scale":0,
			"step":1
		}"
      },
      {
        "code": "device_info",
        "dp_id": 132,
        "type": "Raw",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 16463-----9337,
  "tid": "7abb4aec------96f8"
}
```

How do I map that to a YAML configuration?

Here is my YAML:
```
localtuya:
  host: 192.168.X.X
  device_id: bf5-----x5
  local_key: 1--------8
  friendly_name: Cleverio T-800
  protocol_version: "3.3"
  entities:
  - platform: vacuum
    friendly_name: Van Damme
    id: 5
    idle_status_value: "standby"
    powergo_dp: 2
    battery_dp: 6
    mode_dp: 3
    modes: "standby,random,smart,wall_follow,mop,spiral,left_spiral,right_spiral,right_bow,left_bow,partial_bow,chargego"
    return_mode: "chargego"
    clean_time_dp: 116
    clean_area_dp: 117
    locate_dp: 13
    paused_state: "paused"
    stop_status: "standby"
```
But what should "id" be mapped to? Also, is the rest I've written correct?....

**Pull request merged**
