### PR TITLE
Add debug mode to config flow

### PR DESCRIPTION
**Pull request by postlund**
This PR adds a "debug mode" to the config flow. When filling in the basic info, if ticking the "Enable debug mode", the following step is presented:

DDF01DC9-F0D7-45FD-B2F5-C229B04B479A

From here datapoints can be changed to arbitrary values (assuming supported), so it's great to try things out. It also displays current values of all datapoints in text to make it easier to copy.

Albeit, not my finest work... I think this will be pretty great when we ask for help from our users. Thoughts?

### CODE REVIEW

**Comment by postlund** [comment]
@rospogrigio Did you try this out?

**Comment by postlund** [comment]
I can fix the conflict btw.

**Comment by rospogrigio** [comment]
Sorry no, didn't have the time these days. Will try it soon...

**Comment by rospogrigio** [comment]
I was testing this but I get "unknown error occurred". Here are the logs:


```
2020-10-21 10:51:38 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Sending command heartbeat (device type: type_0d)
2020-10-21 10:51:38 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Send payload: b'{}'
2020-10-21 10:51:38 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Waiting for sequence number -100
2020-10-21 10:51:38 DEBUG (MainThread) [custom_components.localtuya.pytuya] Dispatching message TuyaMessage(seqno=0, cmd=9, retcode=0, payload=b'', crc=2958142211)
2020-10-21 10:51:38 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Got heartbeat response
2020-10-21 10:51:38 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf89d2c3ba66cb83288njv] Decrypted payload: {}
2020-10-21 10:51:40 ERROR (MainThread) [custom_components.localtuya.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/root/etc2/custom_components/localtuya/config_flow.py", line 270, in async_step_basic_info
    self.dps_strings = await validate_input(self.hass, user_input)
  File "/root/etc2/custom_components/localtuya/config_flow.py", line 213, in validate_input
    detected_dps = await _tuya_command(hass, data, "detect_available_dps")
  File "/root/etc2/custom_components/localtuya/config_flow.py", line 194, in _tuya_command
    interface = pytuya.TuyaInterface(

```

**Comment by postlund** [comment]
Are you missing parts of the exception?

**Comment by rospogrigio** [comment]
Obviously yes, sorry, I edited the previous post.

**Comment by postlund** [comment]
@rospogrigio Should be fixed now. Must have totally screwed up a rebase at some point...

**Comment by rospogrigio** [comment]
No luck @postlund , I push "+", enter LocalTuya but I get pushed back to the Integrations list, and cannot proceed. I also tried refreshing the cache, can you please check?

**Comment by postlund** [comment]
Hmm, I tried it yesterday and it worked fine. No errors at all?

**Comment by rospogrigio** [comment]
Nope...

**Comment by rospogrigio** [comment]
@postlund sorry, it was my fault, I had left my main HA instance running so it could not find devices (I believe it should have left the "..." only option, though, instead of going back to the integration list without any message).
Moreover, I cannot use the set_dp. I tried only one switch, a 0a device. 
And, I get several of these errors:

2020-10-22 12:31:49 ERROR (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Heartbeat failed (), disconnecting
Traceback (most recent call last):
  File "/root/etc2/custom_components/localtuya/pytuya/__init__.py", line 346, in heartbeat_loop
    await self.heartbeat()
  File "/root/etc2/custom_components/localtuya/pytuya/__init__.py", line 435, in heartbeat
    return await self.exchange(HEARTBEAT)
  File "/root/etc2/custom_components/localtuya/pytuya/__init__.py", line 407, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/root/etc2/custom_components/localtuya/pytuya/__init__.py", line 206, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 409, in wait_for
    await waiter
concurrent.futures._base.CancelledError

Let me know...

**Comment by postlund** [comment]
@rospogrigio Try now.

**Comment by rospogrigio** [comment]
It worked once, but then I could not redo it, nor reload the DPs.
And I started getting these errors:
```

2020-10-22 13:43:13 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Dispatching sequence number 1
2020-10-22 13:43:13 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Decrypted payload: {"devId":"860687042462ab30b1e5","dps":{"1":false,"7":true,"9":0,"15":0,"18":0,"19":0,"20":2171,"26":0}}
2020-10-22 13:43:13 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Closing connection
2020-10-22 13:43:13 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Connection lost: None
2020-10-22 13:43:13 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Closing connection
2020-10-22 13:43:19 DEBUG (MainThread) [custom_components.localtuya.pytuya] [66058212d8f15bbaf0a8] Sending command heartbeat (device type: type_0a)
2020-10-22 13:43:19 DEBUG (MainThread) [custom_components.localtuya.pytuya] [66058212d8f15bbaf0a8] Send payload: b'{}'
2020-10-22 13:43:19 DEBUG (MainThread) [custom_components.localtuya.pytuya] [66058212d8f15bbaf0a8] Waiting for sequence number -100
2020-10-22 13:43:19 DEBUG (MainThread) [custom_components.localtuya.pytuya] Dispatching message TuyaMessage(seqno=0, cmd=9, retcode=0, payload=b'', crc=2958142211)
2020-10-22 13:43:19 DEBUG (MainThread) [custom_components.localtuya.pytuya] [66058212d8f15bbaf0a8] Got heartbeat response
2020-10-22 13:43:19 DEBUG (MainThread) [custom_components.localtuya.pytuya] [66058212d8f15bbaf0a8] Decrypted payload: {}
2020-10-22 13:43:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Started heartbeat loop
2020-10-22 13:43:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Sending command heartbeat (device type: type_0a)
2020-10-22 13:43:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Send payload: b'{}'
2020-10-22 13:43:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Waiting for sequence number -100
2020-10-22 13:43:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Sending command set (device type: type_0a)
2020-10-22 13:43:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Send payload: b'{"devId":"860687042462ab30b1e5","uid":"860687042462ab30b1e5","t":"1603367007","dps":{"1":true}}'
2020-10-22 13:43:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Waiting for sequence number 1
2020-10-22 13:43:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] Dispatching message TuyaMessage(seqno=0, cmd=9, retcode=0, payload=b'', crc=2958142211)
2020-10-22 13:43:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Got heartbeat response
2020-10-22 13:43:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Decrypted payload: {}
2020-10-22 13:43:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] Dispatching message TuyaMessage(seqno=1, cmd=7, retcode=0, payload=b'', crc=2768611604)
2020-10-22 13:43:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Dispatching sequence number 1
2020-10-22 13:43:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Decrypted payload: {}
2020-10-22 13:43:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Closing connection
2020-10-22 13:43:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Connection lost: None
2020-10-22 13:43:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Closing connection
2020-10-22 13:43:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Started heartbeat loop
2020-10-22 13:43:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Sending command heartbeat (device type: type_0a)
2020-10-22 13:43:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Send payload: b'{}'
2020-10-22 13:43:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Waiting for sequence number -100
2020-10-22 13:43:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Sending command status (device type: type_0a)
2020-10-22 13:43:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Send payload: b'{"gwId":"860687042462ab30b1e5","devId":"860687042462ab30b1e5"}'
2020-10-22 13:43:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Waiting for sequence number 1
2020-10-22 13:43:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] Dispatching message TuyaMessage(seqno=0, cmd=9, retcode=0, payload=b'', crc=2958142211)
2020-10-22 13:43:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Got heartbeat response
2020-10-22 13:43:27 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Decrypted payload: {}
2020-10-22 13:43:28 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Connection lost: [Errno 104] Connection reset by peer
2020-10-22 13:43:28 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Closing connection
2020-10-22 13:43:28 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Wait was aborted for seqno 1
2020-10-22 13:43:28 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Closing connection
2020-10-22 13:43:39 DEBUG (MainThread) [custom_components.localtuya.pytuya] [66058212d8f15bbaf0a8] Sending command heartbeat (device type: type_0a)
2020-10-22 13:43:39 DEBUG (MainThread) [custom_components.localtuya.pytuya] [66058212d8f15bbaf0a8] Send payload: b'{}'
2020-10-22 13:43:39 DEBUG (MainThread) [custom_components.localtuya.pytuya] [66058212d8f15bbaf0a8] Waiting for sequence number -100
2020-10-22 13:43:39 DEBUG (MainThread) [custom_components.localtuya.pytuya] Dispatching message TuyaMessage(seqno=0, cmd=9, retcode=0, payload=b'', crc=2958142211)
2020-10-22 13:43:39 DEBUG (MainThread) [custom_components.localtuya.pytuya] [66058212d8f15bbaf0a8] Got heartbeat response
2020-10-22 13:43:39 DEBUG (MainThread) [custom_components.localtuya.pytuya] [66058212d8f15bbaf0a8] Decrypted payload: {}
2020-10-22 13:43:42 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Started heartbeat loop
2020-10-22 13:43:42 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Sending command heartbeat (device type: type_0a)
2020-10-22 13:43:42 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Send payload: b'{}'
2020-10-22 13:43:42 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Waiting for sequence number -100
2020-10-22 13:43:42 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Sending command status (device type: type_0a)
2020-10-22 13:43:42 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Send payload: b'{"gwId":"860687042462ab30b1e5","devId":"860687042462ab30b1e5"}'
2020-10-22 13:43:42 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Waiting for sequence number 1
2020-10-22 13:43:42 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Connection lost: [Errno 104] Connection reset by peer
2020-10-22 13:43:42 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Closing connection
2020-10-22 13:43:42 ERROR (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Heartbeat failed (), disconnecting
Traceback (most recent call last):
  File "/root/etc2/custom_components/localtuya/pytuya/__init__.py", line 346, in heartbeat_loop
    await self.heartbeat()
  File "/root/etc2/custom_components/localtuya/pytuya/__init__.py", line 435, in heartbeat
    return await self.exchange(HEARTBEAT)
  File "/root/etc2/custom_components/localtuya/pytuya/__init__.py", line 407, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/root/etc2/custom_components/localtuya/pytuya/__init__.py", line 206, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 409, in wait_for
    await waiter
concurrent.futures._base.CancelledError
2020-10-22 13:43:42 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Stopped heartbeat loop
2020-10-22 13:43:42 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Closing connection
2020-10-22 13:43:42 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Wait was aborted for seqno 1
2020-10-22 13:43:42 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Closing connection
2020-10-22 13:43:45 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Started heartbeat loop
2020-10-22 13:43:45 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Sending command heartbeat (device type: type_0a)
2020-10-22 13:43:45 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Send payload: b'{}'
2020-10-22 13:43:45 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Waiting for sequence number -100
2020-10-22 13:43:45 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Sending command status (device type: type_0a)
2020-10-22 13:43:45 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Send payload: b'{"gwId":"860687042462ab30b1e5","devId":"860687042462ab30b1e5"}'
2020-10-22 13:43:45 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Waiting for sequence number 1
2020-10-22 13:43:45 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Connection lost: [Errno 104] Connection reset by peer
2020-10-22 13:43:45 DEBUG (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Closing connection
2020-10-22 13:43:45 ERROR (MainThread) [custom_components.localtuya.pytuya] [860687042462ab30b1e5] Heartbeat failed (), disconnecting
Traceback (most recent call last):
  File "/root/etc2/custom_components/localtuya/pytuya/__init__.py", line 346, in heartbeat_loop
    await self.heartbeat()
  File "/root/etc2/custom_components/localtuya/pytuya/__init__.py", line 435, in heartbeat
    return await self.exchange(HEARTBEAT)
  File "/root/etc2/custom_components/localtuya/pytuya/__init__.py", line 407, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/root/etc2/custom_components/localtuya/pytuya/__init__.py", line 206, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 409, in wait_for
    await waiter
concurrent.futures._base.CancelledError

```

**Comment by postlund** [comment]
Since you get `Connection reset by peer`, are the plug used by somebody else?

**Comment by rospogrigio** [comment]
Nope, I have been viewing the effect with the Jinvoo app, but none of my devices has shown "single connection" needs...

**Comment by rospogrigio** [comment]
Put my phone in airplane mode and retried, with a different switch. The issues I see:
1) after a set_dps, I always get the "concurrent.futures._base.CancelledError", both if successful and unsuccessful
2) after a set_dps, the "current state" label above is empty, and also the DPs drop-down menu is empty, requesting to launch a reload_dps, which is annoying
3) the lazy part of me (that you know quite well by now) would leave one Data type set by default, maybe int or bool since I believe they should be the most used 😉

**Comment by postlund** [comment]
So, I think I figured out what was wrong. I currently do "one-shot" commands, I.e. open a connection, do something and then close the connection. At some point I changed to always re-read the values of all datapoints after doing something. So if you for instance changed a datapoint it would then re-read the values, causing two connection attempts to the device within a very short time span. It seems that there should be a grace period of a second or so between connections. I believe this is the main reason for the problems you see. Now you have to reload manually every time unfortunately. But good enough for now.

I changed `int` to be default and to set precious values as default, to avoid getting empty boxes. Please give it another try!

**Comment by rospogrigio** [comment]
@postlund what do you think of my last considerations? do you want to fix those things or shall we merge?
Let me know

**Comment by postlund** [comment]
@rospogrigio Let me have a look at it tonight again, I'll let you know by then.

**Comment by postlund** [comment]
Ok, so now I have taken a looong time thinking about this. My conclusion is that I don't want to go this road anymore as it turns the config flow into a mess. I have another idea instead that I think is better in some sense.

When implementing #56, we can add all datapoints as state attribute instead. That makes them easy to copy, view and it's possible to extract datapoints and create complex templates that out sensor platforms doesn't support, etc.

To handle manual change of a datapoint, we can add a service instead (e.g. `localtuya.set_dp`). That way we can change datapoints from automations or Lovelace in general. Makes more sense to me. What do you think @rospogrigio?

**Comment by rospogrigio** [comment]
Looks like an excellent idea, in particular if you believe it is making the config flow messy (don't want you to suffer headaches!! 😆 ).
Feel free to close this PR then.
Bye!

**Comment by postlund** [comment]
Yeah, the config flow changes here are a nightmare... I will close this and come back later with another PR or two.

**Pull request closed without merging**
