### PR TITLE
Refactor number entity overrides

### PR DESCRIPTION
**Pull request by markvader**
Relates to issues [929](https://github.com/rospogrigio/localtuya/issues/929), [939](https://github.com/rospogrigio/localtuya/issues/939) & [941](https://github.com/rospogrigio/localtuya/issues/941)
I do not have any suitable tuya devices in use to test against this number entity however the warning in logs "LocaltuyaNumber is overriding deprecated methods on an instance of NumberEntity] is now gone

https://developers.home-assistant.io/blog/2022/06/14/number_entity_refactoring/

### CODE REVIEW

**Comment by pimw1** [comment]
Hi, i checked the fixed on my production system, and it is working as expected. Thank you.

**Review by smarthomefamilyverrips — APPROVED** [review]
These changes worked for me!

**Review by smarthomefamilyverrips — COMMENTED** [review]
Worked for me, Thanks!

**Comment by smarthomefamilyverrips** [comment]
> I tested and while this got rid of the error in the logs, it does not allow changing the temperature units within the ui as intended after 2022.7.0 so I think something is missing in the fix. Before 2022.7.x, temperature pulled in as number entity (in default °C) was automatically converted to ha setting preference (°F for me). 2022.7.0 changed this to °C and unable to change in UI even after these changes.

I not have any device in localtuya with temperature, however I made similar changes to number.py of sonofflan integration and this also did take away the warning message and I am still able to change the temperatures of my TH16's to Fahrenheit or Kelvin instead of Celcius

**Comment by fhornrudd** [comment]
Yeah, maybe my issue is unrelated. I’m able to select the other units but when I click ‘Update’ it does not change the units. Must be related to this component and number entity deprecation in some way as all my other (non-tuya) temperature sensors can change units. I can submit a separate issue in the main release if it does not seem related to this issue.

**Comment by smarthomefamilyverrips** [comment]
> Yeah, maybe my issue is unrelated. I’m able to select the other units but when I click ‘Update’ it does not change the units. Must be related to this component and number entity deprecation in some way as all my other (non-tuya) temperature sensors can change units. I can submit a separate issue in the main release if it does not seem related to this issue.

It could easily be related, unfortunately I have no tuya devices measure temperature to test this also

**Comment by DCG81** [comment]
pls can anyone help, I am getting the same error

Logger: custom_components.localtuya.common
Source: custom_components/localtuya/pytuya/__init__.py:669
Integration: LocalTuya ([documentation](https://github.com/rospogrigio/localtuya/), [issues](https://github.com/rospogrigio/localtuya/issues))
First occurred: 11:59:35 AM (4 occurrences)
Last logged: 11:59:35 AM

[206...5fb] Connect to 192.168.1.145 failed
[447...72b] Connect to 192.168.1.20 failed
[351...e3d] Connect to 192.168.1.58 failed
[206...4be] Connect to 192.168.1.12 failed

**Review by CloCkWeRX — APPROVED** [review]
Looks good when reading https://developers.home-assistant.io/blog/2022/06/14/number_entity_refactoring/

@rospogrigio one for consideration

**Comment by CloCkWeRX** [comment]
Fixes #962

**Comment by CloCkWeRX** [comment]
Fixes #972

**Comment by CloCkWeRX** [comment]
Bump @rospogrigio - tested by others, getting a fair few bug reports around this.

**Comment by wsw70** [comment]
> Bump @rospogrigio - tested by others, getting a fair few bug reports around this.

Yes, there is also https://github.com/rospogrigio/localtuya/issues/972 now. How can we help to have this committed?

**Review by gtricot — APPROVED** [review]

**Review by gtricot — APPROVED** [review]
Seems ok for me.

**Review by rospogrigio — APPROVED** [review]

**Pull request merged**
