### PR TITLE
Fix name issue from pylint changes

### PR DESCRIPTION
**Pull request by postlund**

### CODE REVIEW

**Comment by DavidFFerreira** [comment]
@postlund I did test it now...same errror
image

**Comment by postlund** [comment]
@DavidFFerreira I changed that line in particular, so I think you did not manage to update the files correctly. Verify that you did that.

**Comment by DavidFFerreira** [comment]
image

**Comment by postlund** [comment]
Yes, that's what is on `master`. This PR changes that a bit, check the `Files Changed` tab.

**Comment by DavidFFerreira** [comment]
Its working now. with reinstall master, the file didnt came, so I did change manually and restart. Now its working

**Comment by postlund** [comment]
Good! This is not merged to master yet, so you would have to check it out manually.

**Review by ultratoto14 — APPROVED** [review]

**Pull request merged**
