### PR TITLE
Use debug message for timeout.

### PR DESCRIPTION
**Pull request by ultratoto14**
As we have devices that can be physically off and on like bulbs, this PR is changing the timeout log to a debug one. 
It keeps dumping the stack of any other exception.

### CODE REVIEW

**Comment by postlund** [comment]
I'm a bit torn as this hides a potential "problem" for the user. A timeout can either mean that the device was powered off, but may also mean that the device didn't like what we sent and did not respond. I can approve this now, but we should make it more clear once we have a status sensor.

**Review by postlund — APPROVED** [review]

**Comment by ultratoto14** [comment]
I see your point, i can make it an error log but the stacktrace is not giving anything there

**Comment by postlund** [comment]
The stacktrace is pointless, totally agree. Doesn't matter to me if you log error or debug, you can decide.

**Comment by ultratoto14** [comment]
Ok, so, I'll let it like this. In log level debug we will have a debug message for timeout, in case of other error, it will trace the exception stack and type

**Pull request merged**
