### PR TITLE
Support for ARLEC bi-directional 6-speed ceiling fan

### PR DESCRIPTION
**Pull request by darek-margas**
I've added more speeds on high (I use 5th) and direction control.

### CODE REVIEW

**Comment by denismilanovic** [comment]
Hey @darek-margas have a look at #542, which is presumably being merged in at some point soon and migrates over to using set_percentage rather than the deprecated set_speed. I've also got #417 which is similar to your one (I also have a 6-speec Arlec fan), and I'm waiting to abandon once #542 is merged in.

**Comment by darek-margas** [comment]
> 
> 
> Hey @darek-margas have a look at #542, which is presumably being merged in at some point soon and migrates over to using set_percentage rather than the deprecated set_speed. I've also got #417 which is similar to your one (I also have a 6-speec Arlec fan), and I'm waiting to abandon once #542 is merged in.

Hi, does make sense to use percentage instead, however, how about bi-directional?

**Comment by darek-margas** [comment]
> 
> 
> > Hey @darek-margas have a look at #542, which is presumably being merged in at some point soon and migrates over to using set_percentage rather than the deprecated set_speed. I've also got #417 which is similar to your one (I also have a 6-speec Arlec fan), and I'm waiting to abandon once #542 is merged in.
> 
> Hi, does make sense to use percentage instead, however, how about bi-directional?

Ok, I see it now.

**Comment by lsaadeh** [comment]
Can this PR be closed?

**Comment by darek-margas** [comment]
I believe so if you are not going to merge it.

**Pull request closed without merging**
