### PR TITLE
Add contextual logging where applicable

### LINKED ISSUE #95: Add contextual logging to platforms
Recently I added contextual logging in `pytuya`, so all log points contains the device id. This helps a lot when debugging as it's really hard to decode which log points comes from which device (due to the async network of communication). We should do the same in `LocalTuyaEntity`, so all subclasses can use for instance `self.log` to log with contextual output. We can start by adding device id here as well.

### PR DESCRIPTION
**Pull request by postlund**
I have tried adding device id to all log points now. Not sure if it's the best way, but it's a try. This PR is however very important as many issues are hard to debug without it.

Fixes #95

### CODE REVIEW

**Comment by rospogrigio** [comment]
OK please explain how it should work now...
One more thing: I think it should lighten the logs if we compress the deviceId in the logs, such as:
[ab0c..dd2f] instead of [ab0cd4552ef3ff1dd2f] , what do you think? It would also help align device20 and device22 loggings...

**Comment by postlund** [comment]
The idea is to wrap logger objects with an adapter that adds the device id:

https://docs.python.org/3/howto/logging-cookbook.html#using-loggeradapters-to-impart-contextual-information

It's basically what I did in pytuya before, but I've added a convenience class (`ContextualLogger`) so we can write `self.debug` instead of `self.log.debug` and simplify initialization (code re-use).

Sure, we can compress the id assuming we can do it in such a way it we don't get conflicts. Or we can assume no conflicts and hope for the best...

**Comment by ultratoto14** [comment]
I like the idea of having device id in each log, i'm used to do a tail | grep <id> to identify the log.

As i use many light bulbs, some of them are physically powered off. When log level is info or debug, they all raise exceptions that mess up the logs and make them complex to read.

**Comment by postlund** [comment]
Yeah, all logs about connection errors and such are not very convenient. We need to do something about them (in another PR). In #106 I'm experimenting with only making a connection whenever broadcast messages are received. This removes the need for a re-connect loop, which in turn generate lots of noise when devices are offline. I kinda feel like I want to make that behavior default and using a connect loop (default behavior today) an option. In theory we would only need the broadcast version, but if someone has devices on a different network (broadcast domain), that will not work. So we need to have both.

**Comment by rospogrigio** [comment]
@postlund , I just tried to give a spin to this. Config flow does not work, I believe discovery is broken and I am getting this logs:
```
2020-11-02 17:34:34 INFO (MainThread) [homeassistant.setup] Setting up logger
2020-11-02 17:34:36 ERROR (MainThread) [custom_components.localtuya] failed to set up discovery
Traceback (most recent call last):
  File "/root/etc2/custom_components/localtuya/__init__.py", line 159, in async_setup
    await discovery.start()
  File "/root/etc2/custom_components/localtuya/discovery.py", line 52, in start
    self.listeners = await asyncio.gather(listener, encrypted_listener)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1245, in create_datagram_endpoint
    raise exceptions[0]
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1230, in create_datagram_endpoint
    sock.bind(local_address)
OSError: [Errno 98] Address already in use
```
Also, it's still not very clear to me what I should test, and also I still believe it would be convenient to compress the deviceIDs for readability,
Let me know...

**Comment by postlund** [comment]
Yeah, `address already in use` should be a give-away 😉 Should perhaps add better error output when this happens though.

Basically just look a bit at the outputs and make sure they seem to have decent logging. Also scan the code a bit in case I missed adding contextual logging anywhere.

I can compress output like in your first example. Should work OK.

**Review by rospogrigio — APPROVED** [review]
Looks fine to me, even if I still would prefer the device IDs to be compressed in some way, I find it useless to have such long strings.
And also there are conflicts to be fixed... the good ol' fan.py  ;-)

**Comment by postlund** [comment]
Ah, lol, I actually did implement device id compression but never pushed it... Should be in place now together with conflict fix.

**Pull request merged**
