### PR TITLE
Improve GitHub Actions

### PR DESCRIPTION
**Pull request by KTibow**
I recently announced ha-blueprint:
- With formatting (black + isort for python, prettier for js)
  - It’ll go ahead and pull it, format it, and amend the changes to the last commit.
- With lint
  - JS: Run ESLint to catch syntax errors
  - Python: It runs Hassfest (to catch invalid integrations), HACS (to catch invalid HACS integrations), and flake8 (to catch invalid python).

https://community.home-assistant.io/t/made-a-custom-integration-or-card-ive-created-an-all-in-one-github-action-for-you/235041
This makes it so it auto-checks for HACS, hassfest, and flake8 so you won't have to worry about it being invalid.

### CODE REVIEW

**Comment by rospogrigio** [comment]
@postlund can you review this?

**Comment by postlund** [comment]
Looks good to me, but I'm not sure what to do about the failing check?

**Comment by KTibow** [comment]
Removing HACS check for now.

**Comment by postlund** [comment]
@rospogrigio You will have to remove "validate" as a mandatory check from Actions under Settings now.

**Review by postlund — APPROVED** [review]

**Comment by rospogrigio** [comment]
> @rospogrigio You will have to remove "validate" as a mandatory check from Actions under Settings now.

Mmmm... can't seem to find this option:
image

**Comment by postlund** [comment]
Right, it's probably under `Branches` (then pick `master`).

**Comment by rospogrigio** [comment]
Yep, done!

**Comment by KTibow** [comment]
Any help resolving the conflicts?

**Comment by postlund** [comment]
Are the checks stuck because their corresponding workflow no longer exist after this workflow or is GitHub acting up?

**Comment by postlund** [comment]
@rospogrigio I think you need to update the checks now, since they have changed name.

**Comment by rospogrigio** [comment]
> @rospogrigio I think you need to update the checks now, since they have changed name.

Mmm not sure what you mean... you mean re-run the checks for my PRs?
BTW, what about the python 3.7-3.8-3.9 thing?

**Comment by postlund** [comment]
@rospogrigio Settings -> Branches -> edit master -> only "Tox PR CI" and "Validation And Formatting" should be checked I think. Don't think we need to run on other versions now, just use this.

**Comment by rospogrigio** [comment]
This is the only things I see:
image
Can't find "Tox PR CI" and "Validation And Formatting"...

**Comment by KTibow** [comment]
3.7 and 3.8 are tox. ci is ha-blueprint.

**Pull request merged**
