### PR TITLE
Add discovered HVAC and PRESET options

### PR DESCRIPTION
**Pull request by apbarratt**
This commit adds the HVAC Action Set and Preset Set that I've discovered my Bödenwarme Underfloor Heating thermostat to be using as detailed here: https://github.com/rospogrigio/localtuya/issues/1175

### CODE REVIEW

**Comment by apbarratt** [comment]
Branch rebased.  Would be nice to see this in the next update as I now understand there are others with similar issues that could be fixed with these modes added :)

**Comment by apbarratt** [comment]
I've pulled in some very similar work by @RutgerKe to try and relieve PR reviews.
@rospogrigio  Please do let me know if there are some similar PRs you'd like me to pull in, assuming they are of a similar nature to this, they should merge in nicely without conflicts and you'll have a single PR to review instead of several similar ones :)

**Comment by apbarratt** [comment]
Will this or the the similar PR be reviewed and merged anytime soon?  I appreciate a more dynamic solution was suggested by @rospogrigio at once point but we're four months on and it does not seem the time and motivation has been found to do this yet (not a criticism, I very well know what it's like to not find time or motivation to pursue an idea sometimes!) so I'd have thought just allowing these additional options to be merged in would be a good solution whilst you have folk contributing them :)
If you have a list of similar PRs that I could work through to create a single new options PR, I'd be more than happy to spend a little time combining them together for a single review :)

**Comment by apbarratt** [comment]
Please, please just let this be merged.  It's such a simple change.  I know there's hope for a more dynamic solution, but it's been nearly two years now.  Please just let us add these things in.  It'll be wonderful to add the dynamic stuff later, but does that actually stop things like this being merged?

**Review by rospogrigio — APPROVED** [review]

**Comment by apbarratt** [comment]
Ooo, thank you for approval.  I see the two workflows have succeeded but I'm not sure what the final `ci` one is waiting for, I can't see a workflow file by that name so not sure what it is.  Can you tell I'm not a devops guy by trade? 😅

**Comment by apbarratt** [comment]
Thank you muchly, any chance of a release so HACS can spot the update? :)

**Comment by apbarratt** [comment]
Following up from my previous comment, I still would very much like a release done, but I'd suggest reviewing (and hopefully merging) my latest PR first, which combines a few more HVAC mode PRs :) https://github.com/rospogrigio/localtuya/pull/1793

**Pull request merged**
