### PR TITLE
Allow calling localtuya.set_dp service by non-admin users

### PR DESCRIPTION
**Pull request by ov1d1u**
This PR allows for calling `localtuya.set_dp` services by non-admin users. I'm not sure if the reasoning behind the decision to make this service only available for admin users was from a security standpoint, but I ran in the situation where I added an unsupported service to my configuration then I was unable to trigger a script calling `localtuya.set_dp` because it threw an error (I wrote more about this on #1134).

If there is any reason for this service to be allowed only for admin users, feel free to close this PR.

### CODE REVIEW

**Review by CloCkWeRX — APPROVED** [review]
This seems sensible

**Comment by efpe** [comment]
Hi! Would it be possible to merge this?

**Comment by CloCkWeRX** [comment]
@rospogrigio

**Comment by JD21P** [comment]
Any update to the status of this? I have this issue also. Currently have to add my user as an admin till this issue is fixed.

**Review by rospogrigio — APPROVED** [review]

**Comment by rospogrigio** [comment]
> This seems sensible

I can't think of a real security risk about this and I'd be positive about merging it... can I ask your opinion @CloCkWeRX ?

**Review by CloCkWeRX — APPROVED** [review]
Seems logical to me as well

**Pull request merged**
