### PR TITLE
Add IR Button Support

### PR DESCRIPTION
**Pull request by ynsgnr**
Add code implemented in #1223 by @murilopereirame

Unfortunately that PR is inactive for almost a year and requested changes haven't been made yet, so I have created this PR with the requested changes (separating IR and HVAC changes and adding Base 64 code support)

Tested it and it works offline with a [Tuya Wifi Smart IR Controller](https://nl.aliexpress.com/item/1005005119018257.html?spm=a2g0o.order_detail.order_detail_item.13.44876d76Q7MNzi&gatewayAdapt=glo2nld)

You can get the base64 code from Tuya Cloud as described [here](https://github.com/jasonacox/tinytuya?tab=readme-ov-file#version-33---universal-ir-controller-with-optional-temphumidity)

From the previous PR:

> IR Control
> 
> After some research and a long analysis of the way that Tuya comunicates with generic IR Controls, I've found https://github.com/jasonacox/tinytuya/issues/74 at TinyTuya repo that lead me to that integration.
> 
> Some parts of code, like the convertions of signal was taken from there.
> 
> For now it is a very basic implementation using the Button entity, as Tuya doesn't provide informations about the registered buttons, is necessary that the user configure the device Key by Key into HASS using the Pronto Code of corresponding Key.
> 
> The signal sent by Tuya uses de DP_ID 201, as the device doesn't have a default status, was necessary create a bypass for status checking, so HASS doesn't consider the device unavaliable and to this works propertely, the user needs to input manual DPs for each Key that it's have.
> 
> Ex:
> The user wants to configure 5 keys, it has to add 5 DPs numbers, as 1 to 5, so the Config Flow can provide the option for add new entities into device for the user.
> 
> Another limitation is that ALL keys mus use the DP 201, so I've added a new field to user defines de DP for blast the signal, ignoring provided DPs in first config screen.
> 
> For a better implementation, would be nice to reuse the DP to add new entities; Expand the compatibility of IR Controls, identifying the control version, as described into TinyTuya topic; Group all keys of a gadget, today all keys be part of the device.
> 
> Some Issues/Requests related to IR Control:
> https://github.com/rospogrigio/localtuya/issues/670 https://github.com/rospogrigio/localtuya/issues/882 https://github.com/rospogrigio/localtuya/issues/557
> Resume
> 
> - [x] Support for IR Controls
> - [ ] Reuse DPs
> - [ ] Group keys by gadget
> - [ ] Expand compatibility

### CODE REVIEW

**Comment by ynsgnr** [comment]
@rospogrigio can you take a look at this please

**Comment by NJPYY** [comment]
How do I get base64, you might be using a wrong url

**Comment by ynsgnr** [comment]
> How do I get base64, you might be using a wrong url

Updated the link

**Comment by lindsaymarkward** [comment]
Thanks for this. Can you please explain or point me to instructions on the best way to use this version instead of the current release found by HACS?

**Comment by Andrianjohany** [comment]
Thanks, this PR ~works~ worked well.. I made a huge mistake by accepting the HACS update a couple of days ago. Now all of my IR commands are down and have to make them again :disappointed: 

> Can you please explain or point me to instructions [...]

Here are the detailed steps if it's not too late for you @lindsaymarkward  (or for anyone who is looking for it).
:warning: Do not use the latest base if the PR is left too far behind.

```
sudo apt update 
sudo apt install git
git config pull.rebase false
git config --global user.email "my@domain.tld"
git config --global user.name "me"
git clone https://github.com/rospogrigio/localtuya.git
git remote add btn https://github.com/ynsgnr/localtuya.git
git branch btnmerge
git switch btnmerge
git pull btn master
git switch master
git merge btnmerge
```

Once the merge done, upload the files using Home Assistant Visual Code integration (or scp or whatever) and overwrite the `custom_component/localtuya` files, then reboot HA. 

Still hope for PR merge :crossed_fingers:

**Comment by jabari-12** [comment]
How to configure DP please, I configured a few buttons but none of them are available
图片

**Comment by Andrianjohany** [comment]
The tuya key1 from tuya iot cloud debugging platform is the expected local tuya button code (b64).

Try to manually learn the button code as a custom remote button (instead of using the suggested one)

**Comment by ynsgnr** [comment]
I have switched to a Zigbee IR blaster and ditched Tuya Wifi so can not work on this anymore

**Comment by yarafie** [comment]
> I have switched to a Zigbee IR blaster and ditched Tuya Wifi so can not work on this anymore

Looking for a good zigbee IR Blaster that works in HA also. Which one do u recommend?

**Pull request closed without merging**
