### PR TITLE
Handle 3.4 protocol, fix CI

### PR DESCRIPTION
**Pull request by dulyts**

### CODE REVIEW

**Comment by dulyts** [comment]
Solve #1248 issue

**Comment by nanosilver** [comment]
It should also solve #1425

**Comment by AngelouDi** [comment]
Can confirm it solves #1425 . Please merge.

**Comment by dulyts** [comment]
@rospogrigio could you check my PR please?
Add 3.4 protocol works fine for me in my local HA.
image

**Review by rospogrigio — APPROVED** [review]

**Pull request merged**
