### PR TITLE
#711 Implemented m/p HVAC mode set

### PR DESCRIPTION
**Pull request by Daandeve**
This mode is required for the `Eurom LPL-15`

### CODE REVIEW

**Review by Alloc186 — APPROVED** [review]

**Comment by Daandeve** [comment]
Any progress on validating this small pull request?

**Review by Daandeve — COMMENTED** [review]
Fix for #711

**Comment by CloCkWeRX** [comment]
@Daandeve can you rebase?

**Review by CloCkWeRX — COMMENTED** [review]
@rospogrigio this one seems low risk

**Comment by Daandeve** [comment]
@CloCkWeRX rebased

**Pull request merged**
