### PR TITLE
Fix color temperature to use correct conversion and clamp to allowed range

### PR DESCRIPTION
**Pull request by pabigot**
If `light.turn_on` is invoked with `brightness: 128, color_temp: 500` for a bulb that supports mired range 154..370 in value range 1..255 the calculated color temperature will be negative.  When the bulb receives the command it will turn on, but will fail processing the `4: -153` command to set color_temp and will not send a response packet.
    
At this point `light.toggle` will have no effect because Home Assistant was never told the bulb was turned on, so the same erroneous turn-on command will be re-sent.
    
Fix this by clamping the sent color temperature to the allowed range.

This PR also includes a patch that solves the same problem as #577 but does so by using the core function rather than fixing the local reimplementation.

### CODE REVIEW

**Review by CloCkWeRX — APPROVED** [review]
Seems sensible. Worth adding tests?

**Comment by pabigot** [comment]
I've rebased this so it should be mergeable; it ran into some conflicts with #652 but I believe the change is straightforward.  I've tested the non-reversed path.

> Seems sensible. Worth adding tests?

If there were tests to build on, probably; I don't see any though.

**Comment by CloCkWeRX** [comment]
@rospogrigio - another that seems pretty logical, fairly straightforward. Are you able to OK the actions running?

**Comment by CloCkWeRX** [comment]
Woo, thank you @rospogrigio  :)

**Pull request merged**
