### PR TITLE
Introduced 1_2_3 Commands set for covers

### PR DESCRIPTION
**Pull request by rospogrigio**
Adds 1_2_3 as optional commands set for covers.
**Note: Option parameter changed from open_close_cmds to commands_set .**

### CODE REVIEW

**Comment by pakordo** [comment]
Thanks a lot, works perfectly with device https://templates.blakadder.com/loratap_SC400W.html

**Review by postlund — APPROVED** [review]

**Comment by postlund** [comment]
We should probably start looking at how migration of config entries work. This is a breaking change and everyone using covers will have to re-do their configuration. One strength is to handle breaking changes. Does not work with YAML however as the config format changes.

**Comment by rospogrigio** [comment]
> We should probably start looking at how migration of config entries work. This is a breaking change and everyone using covers will have to re-do their configuration. One strength is to handle breaking changes. Does not work with YAML however as the config format changes.

Did not follow you, can you explain better pleaase?

**Comment by postlund** [comment]
@rospogrigio Since you changed `open_close_cmds` to `command_set`, this will be a breaking change: users must update their configuration. In YAML they have to rename said option and for devices set up via config flow they have to remove the device and re-add it again, otherwise the code will break because `command_set` won't exist. For YAML we have no workaround here. If we rename or change something related to the config format, they will have to update their config. For config entries however we can provide migration paths as config entries are version controlled. We could basically bump the version to 2 and provide a migration function that renames `open_close_cmds` to `command_set` in all existing config entries. The migration happens under-the-hood, so users wouldn't even know about this breaking change (assuming they added via config flow).

https://developers.home-assistant.io/docs/config_entries_config_flow_handler#config-entry-migration

**Pull request merged**
