### PR TITLE
Fix error that happens when in custom scene

### PR DESCRIPTION
**Pull request by ultratoto14**
When in custom scene and light is physically switched off, getting back to on may produce an exception that prevent the light to be available.

### CODE REVIEW

**Comment by postlund** [comment]
@rospogrigio I can assume this is reviewable, right?

**Comment by rospogrigio** [comment]
I don't have a clue, I believe so, maybe @ultratoto14 can answer...

**Comment by postlund** [comment]
Lol, sorry @rospogrigio, I tagged the wrong person 😅

**Comment by ultratoto14** [comment]
@postlund this can be reviewed

**Review by postlund — APPROVED** [review]

**Pull request merged**
