### PR TITLE
Implementing safe default for devices not requiring RESET/Passive functionality - Fix for bug in 4.1.0

### PR DESCRIPTION
**Pull request by sibowler**
Disables RESET functionality unless RESET DPIDs are specified in the device config. 

Hopefully fixes issues #1019 #1015 

For all those requiring RESET (generally for plugs with power monitoring), try 18,19,20 if your device isn't responding.

Have done brief regression test on local system. If others could assist with testing this change to confirm the issue has been correctly identified, that would be appreciated.

### CODE REVIEW

**Comment by sibowler** [comment]
Added some further changes to only enable the Passive DPS restore logic if specifically configured for an entity as there seems to be broader compatibility issues across the gamut of tuya devices. 

This is currently only available for simple entity types (switch/number/select). Other entity types will require specific testing and can be extended at a later stage.

**Comment by sibowler** [comment]
Still TODO: Update the documentation to match the new config entry

**Comment by besiktas97** [comment]
Are the changes merged in the master integration or do we need to wait for a new version in HACS for local tuya?

**Comment by sibowler** [comment]
> Are the changes merged in the master integration or do we need to wait for a new version in HACS for local tuya?

Not yet - Aiming to get this code/fix tested to make sure it addresses all the issues. If you could help test, that would be appreciated.

**Comment by fotis3d** [comment]
@sibowler in order to test it we need to upgrade to the latest and place/replace the red lines you have here at those files right ?

Just to be sure :)

**Comment by sibowler** [comment]
> @sibowler in order to test it we need to upgrade to the latest and place/replace the red lines you have here at those files right ?

Essentially yep -  You need to make sure all the changes are made that are highlighted by the red/green view.

**Comment by fotis3d** [comment]
> > @sibowler in order to test it we need to upgrade to the latest and place/replace the red lines you have here at those files right ?
> 
> Essentially yep - You need to make sure all the changes are made that are highlighted by the red/green view.

I did that but maybe I made a mistake somewhere cause Local Tuya couldn't load on restart. I will recheck. Is it possible to upload somehow and share the changed files to just replace them and test?

**Comment by joe-sydney** [comment]
Seems to have fixed my issue where the fan turned on whenever HA was restarted.

**Comment by JLOFPV** [comment]
I just suffered a blackout again from my circuit breaker configured in your local after the Home Assistant update

**Comment by sibowler** [comment]
> I just suffered a blackout again from my circuit breaker configured in your local after the Home Assistant update

Is that after installing this PR? IF so, do you have any logs from around the incident?

**Comment by JLOFPV** [comment]
> > Acabo de sufrir un apagón nuevamente desde mi disyuntor configurado en su local después de la actualización de Home Assistant
> 
> ¿Eso es después de instalar este PR? Si es así, ¿tiene algún registro de todo el incidente?

Forgive my ignorance. How can I extract a record to facilitate it?

**Comment by rospogrigio** [comment]
Will start testing this PR now on my setup. Why didn't you introduce the Passive option in cover platform too?

**Comment by sibowler** [comment]
> Will start testing this PR now on my setup. Why didn't you introduce the Passive option in cover platform too?

@rospogrigio - Thanks, that would be great. 

Re the passive option for cover. I've disabled the passive functionality for covers in the 4.1.0 release as I this will need some specific testing (and cover devices that are passive) - unfortunately I don't have any Tuya cover devices, so the safer bet seemed to be to disable it for the moment. The framework is there though for when there's a need.

**Comment by rospogrigio** [comment]
> Re the passive option for cover. I've disabled the passive functionality for covers in the 4.1.0 release as I this will need some specific testing (and cover devices that are passive) - unfortunately I don't have any Tuya cover devices, so the safer bet seemed to be to disable it for the moment. The framework is there though for when there's a need.

Ah ok, I see, thank you. Everything seems to run smoothly for the moment, I am planning to merge and release probably tomorrow. More feedbacks would be more than welcome in the meantime.

**Comment by fbloemhof** [comment]
Is it possible that this solves a part of the issues in #1012 ? 

I would like to disable the state restoring after unavailable for fans but not sure where I should do this.

**Comment by pplucky** [comment]
> Seems to have fixed my issue where the fan turned on whenever HA was restarted.

Same here, I had a fan which was turning itself on after every unavailability or HA restart. Fixed after manually implementing this PR.

**Review by rospogrigio — APPROVED** [review]

**Comment by rospogrigio** [comment]
OK after positive feedbacks and me testing for some time without issues, let's merge and release this PR and see if it solves some problems for some users.

**Pull request merged**
